/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softcaster.master_data_mgr.views;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.softcaster.commons.utils.LoggerMgr;
import org.softcaster.easy_pricer_core.data.SecurityMasterData;
import org.softcaster.master_data_mgr.JMasterDataMgr;
import org.softcaster.master_data_mgr.MasterDataFacade;
import org.softcaster.master_data_mgr.dialogs.BondDlg;
import org.softcaster.master_data_mgr.models.MasterDataTableModel;
import org.softcaster.master_data_mgr.models.beans.SecurityBean;
import org.softcaster.master_data_mgr.ui.ZebraTable;

/**
 *
 * @author softc
 */
public class BondPanel extends AbstactMDPanel {

    private final MasterDataFacade masterDataFacade;

    /**
     * Creates new form BondPanel
     *
     * @param masterDataFacade
     */
    public BondPanel(MasterDataFacade masterDataFacade) {
        this.masterDataFacade = masterDataFacade;
        initComponents();
        postInitComponents(bondTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        bondScrollPane = new javax.swing.JScrollPane();
        bondTable = new ZebraTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout(10, 10));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(50, 50, 50));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Bond Master Data");
        lblHeader.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblHeader, java.awt.BorderLayout.NORTH);

        bondTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bondScrollPane.setViewportView(bondTable);

        add(bondScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane bondScrollPane;
    private javax.swing.JTable bondTable;
    private javax.swing.JLabel lblHeader;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void fillModelList() {
        // Crea e setta il model
        SecurityBean prototype = new SecurityBean(null);
        MasterDataTableModel<SecurityBean> model = new MasterDataTableModel<>(prototype);
        bondTable.setModel(model);

        // Popola il model
        refreshModel(model);
    }

    @Override
    protected void acNewActionPerformed(ActionEvent evt) {
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = null;

        if (parentWindow instanceof java.awt.Frame frame) {
            parentFrame = frame;
        }

        BondDlg dialog = new BondDlg(parentFrame, true, null, masterDataFacade);
        dialog.setSize(600, 400);
        // Centra la dialog rispetto al pannello
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        // Post chiusura dialog
        MasterDataTableModel<SecurityBean> model = (MasterDataTableModel<SecurityBean>) bondTable.getModel();
        refreshModel(model);
    }

    @Override
    protected void acModActionPerformed(ActionEvent evt) {
        int rowIndex = bondTable.getSelectedRow();
        if (rowIndex != -1) {
            // 1. CONVERSIONE FONDAMENTALE
            int modelRow = bondTable.convertRowIndexToModel(rowIndex);
            MasterDataTableModel<SecurityBean> model = (MasterDataTableModel<SecurityBean>) bondTable.getModel();
            SecurityBean bean = model.getElementAt(modelRow);
            java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
            java.awt.Frame parentFrame = null;

            if (parentWindow instanceof java.awt.Frame frame) {
                parentFrame = frame;
            }

            BondDlg dialog = new BondDlg(parentFrame, true, bean, masterDataFacade);
            dialog.setSize(600, 400);
            // Centra la dialog rispetto al pannello
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

            // Post chiusura dialog
            refreshModel(model);
        }
    }

    @Override
    protected void acDelActionPerformed(ActionEvent evt) {
        int rowIndex = bondTable.getSelectedRow();
        if (rowIndex != -1) {
            // 1. CONVERSIONE FONDAMENTALE
            int modelRow = bondTable.convertRowIndexToModel(rowIndex);
            MasterDataTableModel<SecurityBean> model = (MasterDataTableModel<SecurityBean>) bondTable.getModel();
            SecurityBean bean = model.getElementAt(modelRow);
            if (JOptionPane.showConfirmDialog(this,
                    "Are you sure to delete item? " + bean.getValueAt(0), JMasterDataMgr.TITLE,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                try {
                    masterDataFacade.getSecurityMasterDataDAO().delete(bean.getSecurityMasterData());
                    refreshModel(model);
                } catch (Exception ex) {
                    LoggerMgr.logError(ex.getLocalizedMessage());
                }
            }
            // Post chiusura dialog
            refreshModel(model);
        }
    }

    @Override
    protected void refreshModel(MasterDataTableModel model) {
        List<SecurityMasterData> bonds = masterDataFacade.getSecurityMasterDataDAO().findAll();
        List<SecurityBean> securityBeanList = new ArrayList<>();
        SecurityBean bean = null;
        for (SecurityMasterData item : bonds) {
            bean = new SecurityBean(item);
            securityBeanList.add(bean);
        }
        model.setData(securityBeanList);
    }
}
