/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softcaster.master_data_mgr.views;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import org.softcaster.easy_pricer_core.data.SecurityMasterData;
import org.softcaster.easy_pricer_core.data.SecurityMasterDataDAO;
import org.softcaster.master_data_mgr.models.BondTableModel;
import org.softcaster.master_data_mgr.ui.DecimalRenderer;
import org.softcaster.master_data_mgr.ui.ZebraTable;

/**
 *
 * @author softc
 */
public class BondPanel extends javax.swing.JPanel {

    private final SecurityMasterDataDAO dao;

    /**
     * Creates new form BondPanel
     *
     * @param dao
     */
    public BondPanel(SecurityMasterDataDAO dao) {
        this.dao = dao;
        initComponents();
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        bondScrollPane = new javax.swing.JScrollPane();
        bondTable = new ZebraTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout(10, 10));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(50, 50, 50));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Bond Master Data");
        lblHeader.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblHeader, java.awt.BorderLayout.NORTH);

        bondTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bondScrollPane.setViewportView(bondTable);

        add(bondScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane bondScrollPane;
    private javax.swing.JTable bondTable;
    private javax.swing.JLabel lblHeader;
    // End of variables declaration//GEN-END:variables

    private void initTable() {
        bondTable.setFillsViewportHeight(true);
        bondTable.setRowHeight(25);
        bondTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));

        // Opzionale: Rimuovi le linee della griglia per un look più moderno (flat)
        bondTable.setShowGrid(false);
        bondTable.setIntercellSpacing(new Dimension(0, 0));

        // Header Elegante
        bondTable.getTableHeader().setOpaque(false);
        bondTable.getTableHeader().setBackground(new Color(230, 230, 230));
        bondTable.getTableHeader().setForeground(Color.BLACK);
        bondTable.getTableHeader().setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        // Più spazio rende i dati più leggibili
        bondTable.setRowHeight(30);

        // Selezione
        bondTable.setSelectionBackground(new Color(184, 207, 229)); // Un blu delicato per la riga selezionata
        bondTable.setSelectionForeground(Color.BLACK);

        bondTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        bondTable.setFocusable(false);
        bondTable.setRowSelectionAllowed(true);

        // Setto il model
        BondTableModel model = new BondTableModel();
        bondTable.setModel(model);

        // Applico renderer
        DecimalRenderer decimalRenderer = new DecimalRenderer();
        bondTable.getColumnModel().getColumn(3).setCellRenderer(decimalRenderer);
        bondTable.getColumnModel().getColumn(5).setCellRenderer(decimalRenderer);

        // Rendo la tabella sortabile
        bondTable.setAutoCreateRowSorter(true);

        // Popolo la tabella
        List<SecurityMasterData> bonds = dao.findAll();
        model.setBondList(bonds);

        // 2. Forza il ricalcolo delle larghezze (IMPORTANTE: fallo dopo che la tabella ha i dati)
        java.awt.EventQueue.invokeLater(() -> {
            autoResizeColumns(bondTable);
        });
    }

    public void autoResizeColumns(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 50; // Larghezza minima iniziale

            // 1. Controlla la larghezza dell'Header
            TableCellRenderer headerRenderer = table.getTableHeader().getDefaultRenderer();
            Component headerComp = headerRenderer.getTableCellRendererComponent(table,
                    columnModel.getColumn(column).getHeaderValue(), false, false, 0, column);
            width = Math.max(headerComp.getPreferredSize().width + 20, width); // +20 per padding

            // 2. Controlla la larghezza dei dati (limita a un numero di righe se la tabella è enorme)
            for (int row = 0; row < Math.min(table.getRowCount(), 100); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + 20, width);
            }

            // Imposta la larghezza calcolata
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }

}
