/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softcaster.master_data_mgr.views;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import org.softcaster.easy_pricer_core.data.Currency;
import org.softcaster.easy_pricer_core.data.CurrencyDAO;
import org.softcaster.master_data_mgr.models.MasterDataTableModel;
import org.softcaster.master_data_mgr.models.beans.CurrencyBean;
import org.softcaster.master_data_mgr.ui.ZebraTable;

/**
 *
 * @author softc
 */
public class ForexPanel extends AbstactMDPanel {

    private final CurrencyDAO dao;

    /**
     * Creates new form ForexPanel
     *
     * @param dao
     */
    public ForexPanel(CurrencyDAO dao) {
        this.dao = dao;
        initComponents();
        postInitComponents(fxTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JPopupMenu();
        acNew = new javax.swing.JMenuItem();
        acMod = new javax.swing.JMenuItem();
        acDel = new javax.swing.JMenuItem();
        lblHeader = new javax.swing.JLabel();
        fxScrollPane = new javax.swing.JScrollPane();
        fxTable = new ZebraTable();

        acNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angular/draft_16dp.png"))); // NOI18N
        acNew.setText("New");
        popUp.add(acNew);

        acMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angular/edit_16dp.png"))); // NOI18N
        acMod.setText("Edit");
        popUp.add(acMod);

        acDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angular/delete_16dp.png"))); // NOI18N
        acDel.setText("Delete");
        popUp.add(acDel);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout(10, 10));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(50, 50, 50));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Currency Master Data");
        lblHeader.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblHeader, java.awt.BorderLayout.NORTH);

        fxTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        fxScrollPane.setViewportView(fxTable);

        add(fxScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acDel;
    private javax.swing.JMenuItem acMod;
    private javax.swing.JMenuItem acNew;
    private javax.swing.JScrollPane fxScrollPane;
    private javax.swing.JTable fxTable;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JPopupMenu popUp;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void fillModelList() {
        // Crea e setta il model
        CurrencyBean prototype = new CurrencyBean(null);
        MasterDataTableModel<CurrencyBean> model = new MasterDataTableModel<>(prototype);
        fxTable.setModel(model);

        // Popola il model
        refreshModel(model);
    }

    @Override
    protected void acNewActionPerformed(ActionEvent evt) {
        System.out.println("acNewActionPerformed");
    }

    @Override
    protected void acModActionPerformed(ActionEvent evt) {
        int rowIndex = fxTable.getSelectedRow();
        if (rowIndex != -1) {
            // 1. CONVERSIONE FONDAMENTALE
            int modelRow = fxTable.convertRowIndexToModel(rowIndex);
            MasterDataTableModel<CurrencyBean> model = (MasterDataTableModel<CurrencyBean>) fxTable.getModel();
            CurrencyBean currency = model.getElementAt(modelRow);
            System.out.println(currency.getValueAt(0));
        }
    }

    @Override
    protected void acDelActionPerformed(ActionEvent evt) {
        System.out.println("acDelActionPerformed");
    }

    @Override
    protected void refreshModel(MasterDataTableModel model) {
        List<Currency> currencies = dao.findAll();
        List<CurrencyBean> currencyBeanList = new ArrayList<>();
        CurrencyBean bean = null;
        for (Currency item : currencies) {
            bean = new CurrencyBean(item);
            currencyBeanList.add(bean);
        }
        model.setData(currencyBeanList);
    }
    
    @Override
    public void downloadAction() {
    }

    @Override
    public void filterAction() {
    }
}
