/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softcaster.master_data_mgr.views;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import org.softcaster.commons.ui.model.FndtTableModel;
import org.softcaster.commons.ui.view.FndtAbstactPanel;
import org.softcaster.core.data.MmFutureMasterData;
import org.softcaster.master_data_mgr.MasterDataFacade;
import org.softcaster.master_data_mgr.dialogs.MmFutureDlg;
import org.softcaster.master_data_mgr.models.MmFutTableModel;
import org.softcaster.master_data_mgr.models.beans.MmFutBean;
import org.softcaster.master_data_mgr.ui.ZebraTable;

/**
 *
 * @author ep
 */
public class MmFuturePanel extends FndtAbstactPanel {

    private final MasterDataFacade masterDataFacade;

    /**
     * Creates new form BondFuturePanel
     *
     * @param masterDataFacade
     */
    public MmFuturePanel(MasterDataFacade masterDataFacade) {
        this.masterDataFacade = masterDataFacade;
        initComponents();
        postInitComponents(mmFutTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        futBondScrollPane = new javax.swing.JScrollPane();
        mmFutTable = new ZebraTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout(10, 10));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("MM Future Master Data");
        lblHeader.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblHeader, java.awt.BorderLayout.NORTH);

        mmFutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        futBondScrollPane.setViewportView(mmFutTable);

        add(futBondScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane futBondScrollPane;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTable mmFutTable;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    @Override
    protected void fillModelList() {
        // Crea e setta il model
        MmFutBean prototype = new MmFutBean(null);
        MmFutTableModel model = new MmFutTableModel(prototype);
        mmFutTable.setModel(model);

        // Popola il model
        refreshModel(model);
    }

    @Override
    protected void acNewActionPerformed(ActionEvent evt) {
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = null;

        if (parentWindow instanceof java.awt.Frame frame) {
            parentFrame = frame;
        }

        MmFutureDlg dialog = new MmFutureDlg(parentFrame, true, null, masterDataFacade);
        dialog.setSize(600, 400);
        // Centra la dialog rispetto al pannello
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        
        // Post chiusura dialog
        MmFutTableModel model = (MmFutTableModel) mmFutTable.getModel();
        refreshModel(model);
    }

    @Override
    protected void acModActionPerformed(ActionEvent evt) {
        int rowIndex = mmFutTable.getSelectedRow();
        if (rowIndex != -1) {
            java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
            java.awt.Frame parentFrame = null;

            if (parentWindow instanceof java.awt.Frame frame) {
                parentFrame = frame;
            }

            // 1. CONVERSIONE FONDAMENTALE
            int modelRow = mmFutTable.convertRowIndexToModel(rowIndex);
            MmFutTableModel model = (MmFutTableModel) mmFutTable.getModel();
            MmFutBean bean = model.getElementAt(modelRow);

            MmFutureDlg dialog = new MmFutureDlg(parentFrame, true, bean, masterDataFacade);
            dialog.setSize(600, 300);
            // Centra la dialog rispetto al pannello
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

            // Post chiusura dialog
            refreshModel(model);
        }
    }

    @Override
    protected void acDelActionPerformed(ActionEvent evt) {
    }

    @Override
    public void downloadAction() {
    }

    @Override
    public void filterAction() {
    }

    @Override
    public void refreshAction() {
    }

    @Override
    protected void refreshModel(FndtTableModel ftm) {
        // Popola il model
        List<MmFutureMasterData> mmFutures = masterDataFacade.getMmFutureMasterDataDAO().findAll();

        List<MmFutBean> mmFutBeanList = new ArrayList<>();
        MmFutBean bean = null;
        for (MmFutureMasterData item : mmFutures) {
            bean = new MmFutBean(item);
            mmFutBeanList.add(bean);
        }
        ftm.setData(mmFutBeanList);
    }

    @Override
    protected void updateModel(FndtTableModel model) {
    }
}
