/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softcaster.easy_pricer_mds.view;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import org.softcaster.commons.ui.ZebraTable;
import org.softcaster.commons.ui.model.FndtTableModel;
import org.softcaster.commons.ui.view.FndtAbstactPanel;
import org.softcaster.commons.utils.LoggerMgr;
import org.softcaster.core.data.InstrumentQuote;
import org.softcaster.core.data.InstrumentQuoteDAO;
import org.softcaster.easy_pricer_mds.MDSFacade;
import org.softcaster.easy_pricer_mds.bean.BondBean;
import org.softcaster.easy_pricer_mds.dialog.BondIQDlg;
import org.softcaster.easy_pricer_mds.dialog.BondPricerDlg;
import org.softcaster.easy_pricer_mds.ui.model.BondTableModel;
import org.softcaster.easy_pricer_mds_core.MarketDataService;
import org.softcaster.easy_pricer_mds_core.TokenItem;
import org.softcaster.provider.enums.Market;
import org.softcaster.provider.enums.RequestType;

/**
 *
 * @author softc
 */
public class BondPanel extends FndtAbstactPanel {

    private final List<BondBean> bondBeanList = new ArrayList<>();
    private MDSFacade mDSFacade = null;

    /**
     * Creates new form ForexPanel
     *
     * @param mDSFacade
     */
    public BondPanel(MDSFacade mDSFacade) {
        this.mDSFacade = mDSFacade;
        initComponents();
        postInitComponents(bondTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JPopupMenu();
        acNew = new javax.swing.JMenuItem();
        acMod = new javax.swing.JMenuItem();
        acDel = new javax.swing.JMenuItem();
        lblHeader = new javax.swing.JLabel();
        fxScrollPane = new javax.swing.JScrollPane();
        bondTable = new ZebraTable();

        acNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angular/draft_16dp.png"))); // NOI18N
        acNew.setText("New");
        popUp.add(acNew);

        acMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angular/edit_16dp.png"))); // NOI18N
        acMod.setText("Edit");
        popUp.add(acMod);

        acDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angular/delete_16dp.png"))); // NOI18N
        acDel.setText("Delete");
        popUp.add(acDel);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout(10, 10));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(50, 50, 50));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Bonds Quotes");
        lblHeader.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblHeader, java.awt.BorderLayout.NORTH);

        bondTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        fxScrollPane.setViewportView(bondTable);

        add(fxScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acDel;
    private javax.swing.JMenuItem acMod;
    private javax.swing.JMenuItem acNew;
    private javax.swing.JTable bondTable;
    private javax.swing.JScrollPane fxScrollPane;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JPopupMenu popUp;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void fillModelList() {
        // Crea e setta il model
        BondBean prototype = new BondBean(null);
        BondTableModel model = new BondTableModel(prototype);
        bondTable.setModel(model);

        // Popola il model
        refreshModelFromDb(model);
    }

    @Override
    protected void acNewActionPerformed(ActionEvent evt) {
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = null;

        if (parentWindow instanceof java.awt.Frame frame) {
            parentFrame = frame;
        }

        BondIQDlg dialog = new BondIQDlg(parentFrame, true, null, mDSFacade);
        dialog.setSize(425, 250);
        // Centra la dialog rispetto al pannello
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        // Post chiusura dialog
        BondTableModel model = (BondTableModel) bondTable.getModel();
        refreshModelFromDb(model);
    }

    @Override
    protected void acModActionPerformed(ActionEvent evt) {
        int rowIndex = bondTable.getSelectedRow();
        if (rowIndex != -1) {
            // 1. CONVERSIONE FONDAMENTALE
            int modelRow = bondTable.convertRowIndexToModel(rowIndex);
            BondTableModel model = (BondTableModel) bondTable.getModel();
            BondBean bean = model.getElementAt(modelRow);
            java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
            java.awt.Frame parentFrame = null;

            if (parentWindow instanceof java.awt.Frame frame) {
                parentFrame = frame;
            }

            BondIQDlg dialog = new BondIQDlg(parentFrame, true, bean, mDSFacade);
            dialog.setSize(425, 250);
            // Centra la dialog rispetto al pannello
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

            // Post chiusura dialog
            refreshModelFromDb(model);
        }
    }

    @Override
    protected void acDelActionPerformed(ActionEvent evt) {
    }

    @Override
    public void downloadAction() {
        // 1. Crea la dialog di attesa
        final JDialog loadingDialog = createLoadingDialog("Saving bond prices ... Please wait.");

        // 2. Crea lo SwingWorker
        // I parametri generici <Void, Void> indicano: <Tipo di ritorno finale, Tipo di dati intermedi>
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {

            @Override
            protected Void doInBackground() throws Exception {
                // Questo metodo gira su un THREAD SEPARATO in background.
                InstrumentQuoteDAO dao = mDSFacade.getInstrumentQuoteDAO();
                if (dao != null) {
                    BondBean bondBean = null;
                    BondTableModel model = (BondTableModel) bondTable.getModel();
                    for (int i = 1; i < model.getRowCount(); i++) {
                        bondBean = (BondBean) model.getElementAt(i);
                        if (bondBean != null) {
                            dao.saveOrUpdate(bondBean.getInstrumentQuote());
                        }
                    }
                }
                return null;
            }

            @Override
            protected void done() {
                // Questo metodo viene eseguito sull'EDT (Thread Grafico) alla fine del download.
                try {
                    // Controlla se ci sono state eccezioni durante il download
                    get();
                } catch (InterruptedException | ExecutionException e) {
                    LoggerMgr.logError(e.getLocalizedMessage());
                    java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(BondPanel.this);
                    javax.swing.JOptionPane.showMessageDialog(parentWindow,
                            "Error during download: " + e.getLocalizedMessage(),
                            "Download Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                } finally {
                    // Chiude la dialog e sblocca la Card del pannello
                    loadingDialog.dispose();
                }
            }
        };
        // 3. Avvia il thread in background
        worker.execute();
        // 4. Mostra la dialog (bloccherà solo l'interfaccia, non il thread in background)
        loadingDialog.setVisible(true);
    }

    @Override
    public void filterAction() {
    }

    @Override
    public void refreshAction() {
        BondTableModel model = (BondTableModel) bondTable.getModel();
        refreshModel(model);
    }

    @Override
    protected void refreshModel(FndtTableModel ftm) {
        // 1. Crea la dialog di attesa
        final JDialog loadingDialog = createLoadingDialog("Downloading Bond prices ... Please wait.");

        // 2. Crea lo SwingWorker
        // I parametri generici <Void, Void> indicano: <Tipo di ritorno finale, Tipo di dati intermedi>
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {

            @Override
            protected Void doInBackground() throws Exception {
                // Questo metodo gira su un THREAD SEPARATO in background.
                updateModel(ftm);
                //Thread.sleep(5000);
                return null;
            }

            @Override
            protected void done() {
                // Questo metodo viene eseguito sull'EDT (Thread Grafico) alla fine del download.
                try {
                    // Controlla se ci sono state eccezioni durante il download
                    get();

                    // Aggiorna i componenti grafici dopo il download (es. ricarica la tabella)
                    //aggiornaTabellaBonds();
                    //statusBarLabel.setText("Data retrieved successfully.");
                } catch (InterruptedException | ExecutionException e) {
                    LoggerMgr.logError(e.getLocalizedMessage());
                    java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(BondPanel.this);
                    javax.swing.JOptionPane.showMessageDialog(parentWindow,
                            "Error during download: " + e.getLocalizedMessage(),
                            "Download Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                } finally {
                    // Chiude la dialog e sblocca la Card del pannello
                    loadingDialog.dispose();
                }
            }
        };
        // 3. Avvia il thread in background
        worker.execute();
        // 4. Mostra la dialog (bloccherà solo l'interfaccia, non il thread in background)
        loadingDialog.setVisible(true);
    }

    public void calculateAction() {
        int rowIndex = bondTable.getSelectedRow();
        if (rowIndex == -1) {
            JOptionPane.showMessageDialog(null, "Select a row to display the pricing dialog!");
            return;
        }

        // 1. CONVERSIONE FONDAMENTALE
        int modelRow = bondTable.convertRowIndexToModel(rowIndex);
        BondTableModel model = (BondTableModel) bondTable.getModel();
        BondBean bean = model.getElementAt(modelRow);

        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = null;

        if (parentWindow instanceof java.awt.Frame frame) {
            parentFrame = frame;
        }

        BondPricerDlg dialog = new BondPricerDlg(parentFrame, true, bean, mDSFacade);
        dialog.setSize(500, 300);
        // Centra la dialog rispetto al pannello
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    @Override
    protected void updateModel(FndtTableModel model) {
        MarketDataService mds = mDSFacade.getMarketDataService();
        BondBean bondBean = null;
        List<TokenItem> tokens = new ArrayList<>();
        for (int i = 1; i < model.getRowCount(); i++) {
            bondBean = (BondBean) model.getElementAt(i);
            if (bondBean != null) {
                tokens.add(new TokenItem(bondBean.getInstrumentQuote().getCode(),
                bondBean.getInstrumentQuote().getProvider()));
            }
        }

        mds.updateSpotPrice(tokens, Market.BONDS);

        for (int i = 1; i < model.getRowCount(); i++) {
            bondBean = (BondBean) model.getElementAt(i);
            if (bondBean != null) {
                bondBean.setAsk(mds.getSpotPrice(bondBean.getInstrumentQuote().getCode(), RequestType.ASK));
                bondBean.setBid(mds.getSpotPrice(bondBean.getInstrumentQuote().getCode(), RequestType.BID));
            }
        }

        model.setData(bondBeanList);
    }

    protected void refreshModelFromDb(FndtTableModel ftm) {
        // Cancella vecchia lista
        bondBeanList.clear();

        // Leggo lista pairs anagrafiche
        List<InstrumentQuote> iqList = mDSFacade.getInstrumentQuoteDAO().findByAssetClass("XRB");
        if (iqList.isEmpty()) {
            return;
        }

        BondBean bean = null;
        for (InstrumentQuote quote : iqList) {
            bean = new BondBean(quote);
            bondBeanList.add(bean);
        }

        ftm.setData(bondBeanList);
    }
}
