/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softcaster.easy_pricer_mds.view;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import org.softcaster.commons.ui.model.FndtTableModel;
import org.softcaster.commons.ui.view.FndtAbstactPanel;
import org.softcaster.easy_pricer_core.data.InstrumentQuote;
import org.softcaster.easy_pricer_mds.MDSFacade;
import org.softcaster.easy_pricer_mds.MarketDataService;
import org.softcaster.easy_pricer_mds.bean.CurrencyPairBean;
import org.softcaster.easy_pricer_mds.dialog.CurrPairIQDlg;
import org.softcaster.easy_pricer_mds.model.CurrPairTableModel;
import org.softcaster.easy_pricer_mds.ui.ZebraTable;
import org.softcaster.marketdataprovider.REQUEST_TYPE;

/**
 *
 * @author softc
 */
public class CurrPairPanel extends FndtAbstactPanel {

    private final List<CurrencyPairBean> forexBeanList = new ArrayList<>();
    private MDSFacade mDSFacade = null;

    /**
     * Creates new form ForexPanel
     *
     * @param mDSFacade
     */
    public CurrPairPanel(MDSFacade mDSFacade) {
        this.mDSFacade = mDSFacade;
        initComponents();
        postInitComponents(fxTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JPopupMenu();
        acNew = new javax.swing.JMenuItem();
        acMod = new javax.swing.JMenuItem();
        acDel = new javax.swing.JMenuItem();
        lblHeader = new javax.swing.JLabel();
        fxScrollPane = new javax.swing.JScrollPane();
        fxTable = new ZebraTable();

        acNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angular/draft_16dp.png"))); // NOI18N
        acNew.setText("New");
        popUp.add(acNew);

        acMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angular/edit_16dp.png"))); // NOI18N
        acMod.setText("Edit");
        popUp.add(acMod);

        acDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angular/delete_16dp.png"))); // NOI18N
        acDel.setText("Delete");
        popUp.add(acDel);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout(10, 10));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(50, 50, 50));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Currency Pairs Quotes");
        lblHeader.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblHeader, java.awt.BorderLayout.NORTH);

        fxTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        fxScrollPane.setViewportView(fxTable);

        add(fxScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acDel;
    private javax.swing.JMenuItem acMod;
    private javax.swing.JMenuItem acNew;
    private javax.swing.JScrollPane fxScrollPane;
    private javax.swing.JTable fxTable;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JPopupMenu popUp;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void fillModelList() {
        // Crea e setta il model
        CurrencyPairBean prototype = new CurrencyPairBean(null);
        CurrPairTableModel model = new CurrPairTableModel(prototype);
        fxTable.setModel(model);

        // Popola il model
        refreshModel(model);
    }

    @Override
    protected void acNewActionPerformed(ActionEvent evt) {
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = null;

        if (parentWindow instanceof java.awt.Frame frame) {
            parentFrame = frame;
        }

        CurrPairIQDlg dialog = new CurrPairIQDlg(parentFrame, true, null, mDSFacade);
        dialog.setSize(425, 200);
        // Centra la dialog rispetto al pannello
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        // Post chiusura dialog
        CurrPairTableModel model = (CurrPairTableModel) fxTable.getModel();
        refreshModel(model);

    }

    @Override
    protected void acModActionPerformed(ActionEvent evt) {
        int rowIndex = fxTable.getSelectedRow();
        if (rowIndex != -1) {
            // 1. CONVERSIONE FONDAMENTALE
            int modelRow = fxTable.convertRowIndexToModel(rowIndex);
            CurrPairTableModel model = (CurrPairTableModel) fxTable.getModel();
            CurrencyPairBean currPair = model.getElementAt(modelRow);
            java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
            java.awt.Frame parentFrame = null;

            if (parentWindow instanceof java.awt.Frame frame) {
                parentFrame = frame;
            }

            CurrPairIQDlg dialog = new CurrPairIQDlg(parentFrame, true, currPair, mDSFacade);
            dialog.setSize(425, 200);
            // Centra la dialog rispetto al pannello
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

            // Post chiusura dialog
            refreshModel(model);
        }
    }

    @Override
    protected void acDelActionPerformed(ActionEvent evt) {
    }

    @Override
    public void downloadAction() {
    }

    @Override
    public void filterAction() {
    }

    @Override
    public void refreshAction() {
        CurrPairTableModel model = (CurrPairTableModel) fxTable.getModel();
        this.refreshModel(model);
    }

    @Override
    protected void refreshModel(FndtTableModel ftm) {
        // Cancella vecchia lista
        forexBeanList.clear();

        // Leggo lista pairs anagrafiche
        List<InstrumentQuote> pairs = mDSFacade.getInstrumentQuoteDAO().findByAssetClass("FSP");
        if (pairs.isEmpty()) {
            return;
        }

        // Aggiorno service
        List<String> tokenList = new ArrayList<>();
        for (InstrumentQuote quote : pairs) {
            tokenList.add(quote.getCode());
        }

        MarketDataService mds = MarketDataService.getInstance();
        mds.updateFxPrice(tokenList, "InvestingComProvider", null);

        CurrencyPairBean bean = null;

        for (InstrumentQuote quote : pairs) {
            quote.setBid(mds.getSpotPrice(quote.getCode(), REQUEST_TYPE.BID));
            quote.setAsk(mds.getSpotPrice(quote.getCode(), REQUEST_TYPE.ASK));
            bean = new CurrencyPairBean(quote);
            forexBeanList.add(bean);
        }

        ftm.setData(forexBeanList);
    }
}
