/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softcaster.easy_pricer_mds.view;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;
import javax.swing.JDialog;
import javax.swing.SwingWorker;
import org.softcaster.commons.ui.ZebraTable;
import org.softcaster.commons.ui.model.FndtTableModel;
import org.softcaster.commons.ui.view.FndtAbstactPanel;
import org.softcaster.commons.utils.LoggerMgr;
import org.softcaster.core.data.InstrumentQuote;
import org.softcaster.core.data.InstrumentQuoteDAO;
import org.softcaster.easy_pricer_mds.MDSFacade;
import org.softcaster.easy_pricer_mds.bean.CurrencyPairBean;
import org.softcaster.easy_pricer_mds.dialog.CurrPairIQDlg;
import org.softcaster.easy_pricer_mds.ui.model.CurrPairTableModel;
import org.softcaster.easy_pricer_mds_core.MarketDataService;
import org.softcaster.easy_pricer_mds_core.TokenItem;
import org.softcaster.provider.enums.Market;
import org.softcaster.provider.enums.RequestType;

/**
 *
 * @author softc
 */
public class CurrPairPanel extends FndtAbstactPanel {

    private final List<CurrencyPairBean> forexBeanList = new ArrayList<>();
    private MDSFacade mDSFacade = null;

    /**
     * Creates new form ForexPanel
     *
     * @param mDSFacade
     */
    public CurrPairPanel(MDSFacade mDSFacade) {
        this.mDSFacade = mDSFacade;
        initComponents();
        postInitComponents(fxTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JPopupMenu();
        acNew = new javax.swing.JMenuItem();
        acMod = new javax.swing.JMenuItem();
        acDel = new javax.swing.JMenuItem();
        lblHeader = new javax.swing.JLabel();
        fxScrollPane = new javax.swing.JScrollPane();
        fxTable = new ZebraTable();

        acNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angular/draft_16dp.png"))); // NOI18N
        acNew.setText("New");
        popUp.add(acNew);

        acMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angular/edit_16dp.png"))); // NOI18N
        acMod.setText("Edit");
        popUp.add(acMod);

        acDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angular/delete_16dp.png"))); // NOI18N
        acDel.setText("Delete");
        popUp.add(acDel);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout(10, 10));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(50, 50, 50));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Currency Pairs Quotes");
        lblHeader.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblHeader, java.awt.BorderLayout.NORTH);

        fxTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        fxScrollPane.setViewportView(fxTable);

        add(fxScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acDel;
    private javax.swing.JMenuItem acMod;
    private javax.swing.JMenuItem acNew;
    private javax.swing.JScrollPane fxScrollPane;
    private javax.swing.JTable fxTable;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JPopupMenu popUp;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void fillModelList() {
        // Crea e setta il model
        CurrencyPairBean prototype = new CurrencyPairBean(null);
        CurrPairTableModel model = new CurrPairTableModel(prototype);
        fxTable.setModel(model);

        // Popola il model
        refreshModelFromDb(model);
    }

    @Override
    protected void acNewActionPerformed(ActionEvent evt) {
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = null;

        if (parentWindow instanceof java.awt.Frame frame) {
            parentFrame = frame;
        }

        CurrPairIQDlg dialog = new CurrPairIQDlg(parentFrame, true, null, mDSFacade);
        dialog.setSize(425, 250);
        // Centra la dialog rispetto al pannello
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        // Post chiusura dialog
        if (dialog.isConfirmed()) {
            CurrPairTableModel model = (CurrPairTableModel) fxTable.getModel();
            refreshModelFromDb(model);
        }
    }

    @Override
    protected void acModActionPerformed(ActionEvent evt) {
        int rowIndex = fxTable.getSelectedRow();
        if (rowIndex != -1) {
            // 1. CONVERSIONE FONDAMENTALE
            int modelRow = fxTable.convertRowIndexToModel(rowIndex);
            CurrPairTableModel model = (CurrPairTableModel) fxTable.getModel();
            CurrencyPairBean currPair = model.getElementAt(modelRow);
            java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
            java.awt.Frame parentFrame = null;

            if (parentWindow instanceof java.awt.Frame frame) {
                parentFrame = frame;
            }

            CurrPairIQDlg dialog = new CurrPairIQDlg(parentFrame, true, currPair, mDSFacade);
            dialog.setSize(425, 250);
            // Centra la dialog rispetto al pannello
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

            // Post chiusura dialog
            if (dialog.isConfirmed()) {
                refreshModelFromDb(model);
            }
        }
    }

    @Override
    protected void acDelActionPerformed(ActionEvent evt) {
    }

    @Override
    public void downloadAction() {
        // 1. Crea la dialog di attesa
        final JDialog loadingDialog = createLoadingDialog("Saving Fx Spot prices ... Please wait.");

        // 2. Crea lo SwingWorker
        // I parametri generici <Void, Void> indicano: <Tipo di ritorno finale, Tipo di dati intermedi>
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {

            @Override
            protected Void doInBackground() throws Exception {
                // Questo metodo gira su un THREAD SEPARATO in background.
                InstrumentQuoteDAO dao = mDSFacade.getInstrumentQuoteDAO();
                if (dao != null) {
                    CurrencyPairBean currencyPairBean = null;
                    CurrPairTableModel model = (CurrPairTableModel) fxTable.getModel();
                    for (int i = 0; i < model.getRowCount(); i++) {
                        currencyPairBean = (CurrencyPairBean) model.getElementAt(i);
                        if (currencyPairBean != null) {
                            dao.saveOrUpdate(currencyPairBean.getInstrumentQuote());
                        }
                    }
                }
                return null;
            }

            @Override
            protected void done() {
                // Questo metodo viene eseguito sull'EDT (Thread Grafico) alla fine del download.
                try {
                    // Controlla se ci sono state eccezioni durante il download
                    get();
                } catch (InterruptedException | ExecutionException e) {
                    LoggerMgr.logError(e.getLocalizedMessage());
                    java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(CurrPairPanel.this);
                    javax.swing.JOptionPane.showMessageDialog(parentWindow,
                            "Error during download: " + e.getLocalizedMessage(),
                            "Download Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                } finally {
                    // Chiude la dialog e sblocca la Card del pannello
                    loadingDialog.dispose();
                }
            }
        };
        // 3. Avvia il thread in background
        worker.execute();
        // 4. Mostra la dialog (bloccherà solo l'interfaccia, non il thread in background)
        loadingDialog.setVisible(true);
    }

    @Override
    public void filterAction() {
    }

    @Override
    public void refreshAction() {
        CurrPairTableModel model = (CurrPairTableModel) fxTable.getModel();
        refreshModel(model);
    }

    /**
     *
     * @param ftm
     */
    @Override
    protected void refreshModel(FndtTableModel ftm) {

        // 1. Crea la dialog di attesa
        final JDialog loadingDialog = createLoadingDialog("Downloading Fx Spot prices ... Please wait.");

        // 2. Crea lo SwingWorker
        // I parametri generici <Void, Void> indicano: <Tipo di ritorno finale, Tipo di dati intermedi>
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {

            @Override
            protected Void doInBackground() throws Exception {
                // Questo metodo gira su un THREAD SEPARATO in background.
                updateModel(ftm);
                return null;
            }

            @Override
            protected void done() {
                // Questo metodo viene eseguito sull'EDT (Thread Grafico) alla fine del download.
                try {
                    // Controlla se ci sono state eccezioni durante il download
                    get();

                } catch (InterruptedException | ExecutionException e) {
                    LoggerMgr.logError(e.getLocalizedMessage());
                    java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(CurrPairPanel.this);
                    javax.swing.JOptionPane.showMessageDialog(parentWindow,
                            "Error during download: " + e.getLocalizedMessage(),
                            "Download Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                } finally {
                    // Chiude la dialog e sblocca la Card del pannello
                    loadingDialog.dispose();
                }
            }
        };
        // 3. Avvia il thread in background
        worker.execute();
        // 4. Mostra la dialog (bloccherà solo l'interfaccia, non il thread in background)
        loadingDialog.setVisible(true);
    }

    @Override
    protected void updateModel(FndtTableModel model) {
        List<TokenItem> tokens = new ArrayList<>();
        for (CurrencyPairBean bean : forexBeanList) {
            tokens.add(new TokenItem(bean.getInstrumentQuote().getCode(), bean.getInstrumentQuote().getProvider()));
        }
        MarketDataService mds = mDSFacade.getMarketDataService();
        mds.updateSpotPrice(tokens, Market.CURRENCIES);

        // Leggo lista pairs anagrafiche
        List<InstrumentQuote> pairs = mDSFacade.getInstrumentQuoteDAO().findByAssetClass("FSP");
        if (pairs.isEmpty()) {
            return;
        }

        // Aggiorno dati in memoria
        for (CurrencyPairBean bean : forexBeanList) {
            bean.setBid(mds.getSpotPrice(bean.getInstrumentQuote().getCode(), RequestType.BID));
            bean.setAsk(mds.getSpotPrice(bean.getInstrumentQuote().getCode(), RequestType.ASK));
        }

        model.setData(forexBeanList);
    }

    protected void refreshModelFromDb(FndtTableModel ftm) {
        // Cancella vecchia lista
        forexBeanList.clear();

        // Leggo lista pairs anagrafiche
        List<InstrumentQuote> pairs = mDSFacade.getInstrumentQuoteDAO().findByAssetClass("FSP");
        if (pairs.isEmpty()) {
            return;
        }

        CurrencyPairBean bean = null;

        for (InstrumentQuote quote : pairs) {
            bean = new CurrencyPairBean(quote);
            forexBeanList.add(bean);
        }

        ftm.setData(forexBeanList);
    }
}
