/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softcaster.easy_pricer_mds.view;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import org.softcaster.commons.utils.LoggerMgr;
import org.softcaster.easy_pricer_mds.MarketDataNotFoundException;
import org.softcaster.easy_pricer_mds.MarketDataService;
import org.softcaster.easy_pricer_mds.bean.FxFutBean;
import org.softcaster.easy_pricer_mds.model.MDSTableModel;
import org.softcaster.easy_pricer_mds.ui.ZebraTable;

/**
 *
 * @author softc
 */
public class FxFutPanel extends AbstactMDPanel {

    private final List<FxFutBean> fxFutBeanList = new ArrayList<>();

    /**
     * Creates new form ForexPanel
     *
     */
    public FxFutPanel() {
        initComponents();
        postInitComponents(fxFutTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JPopupMenu();
        acNew = new javax.swing.JMenuItem();
        acMod = new javax.swing.JMenuItem();
        acDel = new javax.swing.JMenuItem();
        lblHeader = new javax.swing.JLabel();
        fxFutScrollPane = new javax.swing.JScrollPane();
        fxFutTable = new ZebraTable();

        acNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angular/draft_16dp.png"))); // NOI18N
        acNew.setText("New");
        popUp.add(acNew);

        acMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angular/edit_16dp.png"))); // NOI18N
        acMod.setText("Edit");
        popUp.add(acMod);

        acDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angular/delete_16dp.png"))); // NOI18N
        acDel.setText("Delete");
        popUp.add(acDel);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout(10, 10));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(50, 50, 50));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Fx Future Quotes");
        lblHeader.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblHeader, java.awt.BorderLayout.NORTH);

        fxFutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        fxFutScrollPane.setViewportView(fxFutTable);

        add(fxFutScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acDel;
    private javax.swing.JMenuItem acMod;
    private javax.swing.JMenuItem acNew;
    private javax.swing.JScrollPane fxFutScrollPane;
    private javax.swing.JTable fxFutTable;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JPopupMenu popUp;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void fillModelList() {
        // Crea e setta il model
        FxFutBean prototype = new FxFutBean("", 0., 0.);
        MDSTableModel<FxFutBean> model = new MDSTableModel<>(prototype);
        fxFutTable.setModel(model);

        // Popola il model
        refreshModel(model);
    }

    @Override
    protected void acNewActionPerformed(ActionEvent evt) {
    }

    @Override
    protected void acModActionPerformed(ActionEvent evt) {
    }

    @Override
    protected void acDelActionPerformed(ActionEvent evt) {
    }

    @Override
    protected void refreshModel(MDSTableModel model) {
        try {
            fxFutBeanList.clear();

            MarketDataService service = MarketDataService.getInstance();
            double price = service.getSpotPrice("6EJ6");
            FxFutBean bean = new FxFutBean("6EJ6", price, price);
            fxFutBeanList.add(bean);

            price = service.getSpotPrice("6EK6");
            bean = new FxFutBean("6EK6", price, price);
            fxFutBeanList.add(bean);

            price = service.getSpotPrice("6EM6");
            bean = new FxFutBean("6EM6", price, price);
            fxFutBeanList.add(bean);

            price = service.getSpotPrice("6EN6");
            bean = new FxFutBean("6EN6", price, price);
            fxFutBeanList.add(bean);

            price = service.getSpotPrice("6EU6");
            bean = new FxFutBean("6EU6", price, price);
            fxFutBeanList.add(bean);

            price = service.getSpotPrice("6EZ6");
            bean = new FxFutBean("6EZ6", price, price);
            fxFutBeanList.add(bean);

            price = service.getSpotPrice("6BJ6");
            bean = new FxFutBean("6BJ6", price, price);
            fxFutBeanList.add(bean);

            price = service.getSpotPrice("6BK6");
            bean = new FxFutBean("6BK6", price, price);
            fxFutBeanList.add(bean);

            price = service.getSpotPrice("6BM6");
            bean = new FxFutBean("6BM6", price, price);
            fxFutBeanList.add(bean);

            model.setData(fxFutBeanList);
        } catch (MarketDataNotFoundException ex) {
            LoggerMgr.logError(ex.getLocalizedMessage());
        }
    }

    @Override
    public void downloadAction() {
    }

    @Override
    public void filterAction() {
    }

    @Override
    public void refreshAction() {
        MarketDataService service = MarketDataService.getInstance();
        double price = service.getSpotPrice("6EM6");
        System.out.println(price);
    }
}
