/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softcaster.easy_pricer_mds.view;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;
import javax.swing.JDialog;
import javax.swing.SwingWorker;
import org.softcaster.commons.ui.ZebraTable;
import org.softcaster.commons.ui.model.FndtTableModel;
import org.softcaster.commons.ui.view.FndtAbstactPanel;
import org.softcaster.commons.utils.LoggerMgr;
import org.softcaster.core.data.YieldCurve;
import org.softcaster.core.data.YieldCurveDAO;
import org.softcaster.easy_pricer_mds.MDSFacade;
import org.softcaster.easy_pricer_mds.bean.YieldCurveBean;
import org.softcaster.easy_pricer_mds.dialog.YieldCurveDlg;
import org.softcaster.easy_pricer_mds.ui.model.YieldCurveModel;
import org.softcaster.easy_pricer_mds_core.MarketDataService;

/**
 *
 * @author ep
 */
public class YieldCurvePanel extends FndtAbstactPanel {

    private final List<YieldCurveBean> yieldCurveBeanList = new ArrayList<>();
    private MDSFacade mDSFacade = null;

    /**
     * Creates new form YieldCurvePanel
     *
     * @param mDSFacade
     */
    public YieldCurvePanel(MDSFacade mDSFacade) {
        this.mDSFacade = mDSFacade;
        initComponents();
        postInitComponents(ycTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        ycScrollPane = new javax.swing.JScrollPane();
        ycTable = new ZebraTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout(10, 10));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(50, 50, 50));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Yield Curves");
        lblHeader.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblHeader, java.awt.BorderLayout.NORTH);

        ycTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ycScrollPane.setViewportView(ycTable);

        add(ycScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void refreshAction() {
        YieldCurveModel model = (YieldCurveModel) ycTable.getModel();
        this.updateModel(model);
    }

    @Override
    protected void fillModelList() {
        // Crea e setta il model
        YieldCurveBean prototype = new YieldCurveBean(null);
        YieldCurveModel model = new YieldCurveModel(prototype);
        ycTable.setModel(model);

        // Popola il model
        refreshModel(model);
    }

    @Override
    protected void refreshModel(FndtTableModel model) {
        yieldCurveBeanList.clear();
        YieldCurveDAO dao = mDSFacade.getYieldCurveDAO();
        List<YieldCurve> curves = dao.findAll();
        YieldCurveBean bean = null;
        for (YieldCurve yc : curves) {
            bean = new YieldCurveBean(yc);
            yieldCurveBeanList.add(bean);
        }

        model.setData(yieldCurveBeanList);
    }

    private void updateTable(FndtTableModel model) {
        for(YieldCurveBean bean: yieldCurveBeanList) {
            if(bean != null && bean.getYieldCurve() != null && !bean.getYieldCurve().getProvider().isBlank()) {
                MarketDataService mds = mDSFacade.getMarketDataService();
                mds.updateYieldCurve(bean.getYieldCurve().getProvider(), bean.getYieldCurve().getCode());
            }
        }
    }

    @Override
    protected void updateModel(FndtTableModel model) {
        // 1. Crea la dialog di attesa
        final JDialog loadingDialog = createLoadingDialog("Downloading rates ... Please wait.");

        // 2. Crea lo SwingWorker
        // I parametri generici <Void, Void> indicano: <Tipo di ritorno finale, Tipo di dati intermedi>
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {

            @Override
            protected Void doInBackground() throws Exception {
                // Questo metodo gira su un THREAD SEPARATO in background.
                updateTable(model);
                //Thread.sleep(5000);
                return null;
            }

            @Override
            protected void done() {
                // Questo metodo viene eseguito sull'EDT (Thread Grafico) alla fine del download.
                try {
                    // Controlla se ci sono state eccezioni durante il download
                    get();

                    // Aggiorna i componenti grafici dopo il download (es. ricarica la tabella)
                    //aggiornaTabellaBonds();
                    //statusBarLabel.setText("Data retrieved successfully.");
                } catch (InterruptedException | ExecutionException e) {
                    LoggerMgr.logError(e.getLocalizedMessage());
                    java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(YieldCurvePanel.this);
                    javax.swing.JOptionPane.showMessageDialog(parentWindow,
                            "Error during download: " + e.getLocalizedMessage(),
                            "Download Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                } finally {
                    // Chiude la dialog e sblocca la Card del pannello
                    loadingDialog.dispose();
                }
            }
        };
        // 3. Avvia il thread in background
        worker.execute();
        // 4. Mostra la dialog (bloccherà solo l'interfaccia, non il thread in background)
        loadingDialog.setVisible(true);
    }

    @Override
    protected void acNewActionPerformed(ActionEvent evt) {
    }

    @Override
    protected void acModActionPerformed(ActionEvent evt) {
        int rowIndex = ycTable.getSelectedRow();
        if (rowIndex != -1) {
            // 1. CONVERSIONE FONDAMENTALE
            int modelRow = ycTable.convertRowIndexToModel(rowIndex);
            YieldCurveModel model = (YieldCurveModel) ycTable.getModel();
            YieldCurveBean bean = model.getElementAt(modelRow);
            java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
            java.awt.Frame parentFrame = null;

            if (parentWindow instanceof java.awt.Frame frame) {
                parentFrame = frame;
            }

            YieldCurveDlg dialog = new YieldCurveDlg(parentFrame, true, bean, mDSFacade);
            dialog.setSize(425, 250);
            // Centra la dialog rispetto al pannello
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

            // Post chiusura dialog
            refreshModel(model);
        }
    }

    @Override
    protected void acDelActionPerformed(ActionEvent evt) {
    }

    @Override
    public void downloadAction() {
    }

    @Override
    public void filterAction() {
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblHeader;
    private javax.swing.JScrollPane ycScrollPane;
    private javax.swing.JTable ycTable;
    // End of variables declaration//GEN-END:variables
}
