
# Specifica che NON \u00e8 un'applicazione web (evita errori all'avvio)
#spring.main.web-application-type=none
# Configurazione Server
server.port=8083

# End Point
server.servlet.context-path=/api/v1

# Configurazione RabbitMQ (Docker)
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

# Configurazione della logica di riproca (Retry)
# Se l'elaborazione fallisce, riprova 3 volte prima di mandare il messaggio in errore
#spring.rabbitmq.listener.simple.retry.enabled=true
#spring.rabbitmq.listener.simple.retry.max-attempts=3
#spring.rabbitmq.listener.simple.retry.initial-interval=3000ms

# Configurazione Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sofie
spring.datasource.username=sofie
spring.datasource.password=sofie
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurazione JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

# Configurazione Logging
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO

# Configurazione scripts
app.scripts.path=./easy_pricer_proc/scripts/
