/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.softcaster.easy_pricer_mds;

import jakarta.annotation.PostConstruct;
import java.awt.CardLayout;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.tree.DefaultMutableTreeNode;
import org.softcaster.commons.utils.LoggerMgr;
import static org.softcaster.easy_pricer_mds.AppTreeItem.CURR_PAIR;
import org.softcaster.easy_pricer_mds.model.MDSNode;
import org.softcaster.easy_pricer_mds.model.TreeModel;
import org.softcaster.easy_pricer_mds.ui.MDSTreeCellRenderer;
import org.softcaster.easy_pricer_mds.view.CurrPairPanel;
import org.softcaster.easy_pricer_mds.view.HomePanel;
import org.springframework.stereotype.Component;

/**
 *
 * @author ep
 */
@Component
public class JMarketDataService extends javax.swing.JFrame {

    public static final String TITLE = "Market Data Service 1.0";

    private AppCard currentCard;
    private Map<AppCard, javax.swing.JPanel> cardMap = new HashMap<>();

    /**
     * Creates new form JMarketDataService
     */
    public JMarketDataService() {
        try {
            // Imposta il tema Windows
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            initComponents();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JMarketDataService.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    @PostConstruct
    public void init() {

        // Forza l'esecuzione sul thread di Swing per evitare race conditions
        java.awt.EventQueue.invokeLater(() -> {

            // Titolo
            this.setTitle(TITLE);

            // Icona
            ImageIcon img = new ImageIcon(getClass().getResource("/images/favicon.png"));
            setIconImage(img.getImage());

            // Set the initial size of the window
            setSize(1200, 800);

            // Finestra centrata nello schermo
            setLocationRelativeTo(null);

            navigator.setModel(TreeModel.buildTree());
            navigator.setCellRenderer(new MDSTreeCellRenderer());
            navigator.addTreeSelectionListener(e -> {
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) navigator.getLastSelectedPathComponent();

                if (node == null) {
                    return; // Nessuna selezione
                }
                Object userObject = node.getUserObject();
                if (node.isLeaf() && userObject instanceof MDSNode data) {

                    // Recupera il CardLayout dal mainPanel
                    CardLayout cl = (CardLayout) (mainPanel.getLayout());

                    // Logica per decidere quale pannello mostrare in base al tipo
                    switch (data.getType()) {
                        case CURR_PAIR -> {
                            cl.show(mainPanel, AppCard.CURR_PAIR_CARD.name());
                            currentCard = AppCard.CURR_PAIR_CARD;
                        }
                        default -> {
                            cl.show(mainPanel, AppCard.DEFAULT_CARD.name());
                            currentCard = AppCard.DEFAULT_CARD;
                        }
                    }

                    // Opzionale: Carica i dati specifici nel pannello appena mostrato
                    // bondPanel.loadData(data.getId()); 
                }
            });

            addPanels();
            // Sovrascrive qualsiasi impostazione precedente
            this.setDefaultCloseOperation(javax.swing.JFrame.DO_NOTHING_ON_CLOSE);

            // Rimuovi eventuali listener esistenti per evitare doppie chiamate
            for (java.awt.event.WindowListener wl : this.getWindowListeners()) {
                this.removeWindowListener(wl);
            }

            this.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    exitAction();
                }
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        sideNav = new javax.swing.JPanel();
        sideNavScrollPane = new javax.swing.JScrollPane();
        navigator = new javax.swing.JTree();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        splitPane.setDividerLocation(200);

        sideNav.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        sideNav.setLayout(new java.awt.BorderLayout(10, 0));

        sideNavScrollPane.setPreferredSize(new java.awt.Dimension(80, 362));
        sideNavScrollPane.setViewportView(navigator);

        sideNav.add(sideNavScrollPane, java.awt.BorderLayout.CENTER);

        splitPane.setLeftComponent(sideNav);

        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        mainPanel.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(mainPanel);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 571, 424);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTree navigator;
    private javax.swing.JPanel sideNav;
    private javax.swing.JScrollPane sideNavScrollPane;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
    private void exitAction() {
        if (JOptionPane.showConfirmDialog(this,
                "Are you sure?", TITLE,
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            LoggerMgr.logInfo("Bye bye!");
            System.exit(0);
        }
    }

    private void addPanels() {

        // 1. Istanzia i pannelli
        JPanel defaultPanel = new HomePanel();
        cardMap.put(AppCard.DEFAULT_CARD, defaultPanel);
        JPanel cpPanel = new CurrPairPanel();
        cardMap.put(AppCard.CURR_PAIR_CARD, cpPanel);

        // 2. Aggiunge al mainPanel assegnando un nome (la "Chiave" della Card)
        mainPanel.add(defaultPanel, AppCard.DEFAULT_CARD.name());
        mainPanel.add(cpPanel, AppCard.CURR_PAIR_CARD.name());

        // 3. Mostra la card iniziale
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, AppCard.DEFAULT_CARD.name());
    }
}
