<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.softcaster</groupId>    
    <artifactId>easy_pricer_mds_core</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <exec.mainClass>org.softcaster.easy_pricer_mds_core.Easy_pricer_mds_core</exec.mainClass>
    </properties>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>provider</artifactId>
            <version>1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.softcaster</groupId>
                    <artifactId>engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>        
    </dependencies>


</project>