<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://apache.org" xmlns:xsi="http://w3.org" xsi:schemaLocation="http://apache.org http://apache.org">
    <modelVersion>4.0.0</modelVersion>

    <!-- 1. Aggiungi il Parent di Spring Boot per ereditare le versioni delle dipendenze -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.3</version>
        <relativePath/> 
    </parent>

    <groupId>org.softcaster.easy_pricer_mds_core</groupId>    
    <artifactId>mds_core</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
    
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- Con Spring Boot è preferibile usare la proprietà release -->
        <maven.compiler.release>17</maven.compiler.release>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <!-- Dipendenze interne del tuo progetto -->
        <dependency>
            <groupId>org.softcaster.core.data</groupId>
            <artifactId>core</artifactId>
            <version>1.0</version>
        </dependency>              
        <dependency>
            <groupId>org.softcaster.commons</groupId>
            <artifactId>foundation</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>org.softcaster.provider</groupId>
            <artifactId>provider</artifactId>
            <version>1.0</version>
        </dependency>        
        <dependency>
            <groupId>org.softcaster.engine</groupId>
            <artifactId>engine</artifactId>
            <version>1.0</version>
        </dependency>        

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- NOTA BENE: Non inserire il plugin 
                 spring-boot-maven-plugin con l'operazione 'repackage', altrimenti 
                 il JAR diventerà un file eseguibile e l'applicazione principale non 
                 riuscirà più a importare le sue classi. -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
            </plugin>
        </plugins>
    </build>
</project>
