/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.softcaster.master_data_mgr.dialogs;

import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.softcaster.commons.types.Date;
import org.softcaster.commons.utils.Converter;
import org.softcaster.commons.utils.LoggerMgr;
import org.softcaster.core.data.BondFutureMasterData;
import org.softcaster.core.data.Currency;
import org.softcaster.core.data.Daycount;
import org.softcaster.core.data.SettlementType;
import org.softcaster.master_data_mgr.MasterDataFacade;
import org.softcaster.master_data_mgr.models.beans.FutBondBean;

/**
 *
 * @author ep
 */
public class BondFutureDlg extends javax.swing.JDialog {

    private FutBondBean bean = null;
    private MasterDataFacade masterDataFacade = null;
    private List<javax.swing.JTextField> fieldsToValidate;
    private boolean isInsert = true;

    /**
     * Creates new form BondFutureDlg
     *
     * @param parent
     * @param modal
     * @param bean
     * @param masterDataFacade
     */
    public BondFutureDlg(java.awt.Frame parent, boolean modal, FutBondBean bean, MasterDataFacade masterDataFacade) {
        super(parent, modal);
        this.bean = bean;
        this.masterDataFacade = masterDataFacade;
        initComponents();
        postInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        fieldPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIsin = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtContractValue = new javax.swing.JTextField();
        txtTickSize = new javax.swing.JTextField();
        txtInitMargin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIssueDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtExpiryDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtLastTradingDate = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        additionalPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtContractCode = new javax.swing.JTextField();
        cbCurrency = new javax.swing.JComboBox<>();
        cbDaycount = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel12 = new javax.swing.JLabel();
        cbSettlementType = new javax.swing.JComboBox<>();
        btnPanel = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bond Future");
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        mainPanel.setLayout(new java.awt.GridBagLayout());

        fieldPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        fieldPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("ISIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtIsin, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtDescription, gridBagConstraints);

        jLabel3.setText("Contract Value");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Tick Size");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel4, gridBagConstraints);

        txtContractValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtContractValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContractValueFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtContractValue, gridBagConstraints);

        txtTickSize.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTickSize.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTickSizeFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtTickSize, gridBagConstraints);

        txtInitMargin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtInitMargin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInitMarginFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtInitMargin, gridBagConstraints);

        jLabel5.setText("Initial Margin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Issue Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel6, gridBagConstraints);

        txtIssueDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIssueDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIssueDateFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtIssueDate, gridBagConstraints);

        jLabel7.setText("Expity Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel7, gridBagConstraints);

        txtExpiryDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtExpiryDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtExpiryDateFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtExpiryDate, gridBagConstraints);

        jLabel8.setText("Last Trading Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel8, gridBagConstraints);

        txtLastTradingDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLastTradingDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLastTradingDateFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtLastTradingDate, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        fieldPanel.add(filler1, gridBagConstraints);

        tabbedPane.addTab("Specification", fieldPanel);

        additionalPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        additionalPanel.setLayout(new java.awt.GridBagLayout());

        jLabel9.setText("Contract Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Currency");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Daycount");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(txtContractCode, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbCurrency, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbDaycount, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        additionalPanel.add(filler3, gridBagConstraints);

        jLabel12.setText("Settlement Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbSettlementType, gridBagConstraints);

        tabbedPane.addTab("Additional", additionalPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(tabbedPane, gridBagConstraints);

        btnPanel.setLayout(new java.awt.GridBagLayout());

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(btnSave, gridBagConstraints);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(btnCancel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        btnPanel.add(filler2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(btnPanel, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 606, 307);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        boolean isValid = validateFields() && validateIntegrity();
        if (!isValid) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please fill in all the required fields.", // Messaggio
                    "Validation Error", // Titolo
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        } else {
            if (!saveBean()) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Error during save.\n See log file for more details.", // Messaggio
                        "Save Error", // Titolo
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtContractValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContractValueFocusLost
        MDDialogHelper.textFieldDoubleFocusLost(txtContractValue);
    }//GEN-LAST:event_txtContractValueFocusLost

    private void txtTickSizeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTickSizeFocusLost
        MDDialogHelper.textFieldDoubleFocusLost(txtTickSize);
    }//GEN-LAST:event_txtTickSizeFocusLost

    private void txtInitMarginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInitMarginFocusLost
        MDDialogHelper.textFieldDoubleFocusLost(txtInitMargin);
    }//GEN-LAST:event_txtInitMarginFocusLost

    private void txtIssueDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIssueDateFocusLost
        MDDialogHelper.textFieldDateFocusLost(txtIssueDate);
    }//GEN-LAST:event_txtIssueDateFocusLost

    private void txtExpiryDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtExpiryDateFocusLost
        MDDialogHelper.textFieldDateFocusLost(txtExpiryDate);
    }//GEN-LAST:event_txtExpiryDateFocusLost

    private void txtLastTradingDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastTradingDateFocusLost
        MDDialogHelper.textFieldDateFocusLost(txtLastTradingDate);
    }//GEN-LAST:event_txtLastTradingDateFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel additionalPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Currency> cbCurrency;
    private javax.swing.JComboBox<Daycount> cbDaycount;
    private javax.swing.JComboBox<SettlementType> cbSettlementType;
    private javax.swing.JPanel fieldPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField txtContractCode;
    private javax.swing.JTextField txtContractValue;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtExpiryDate;
    private javax.swing.JTextField txtInitMargin;
    private javax.swing.JTextField txtIsin;
    private javax.swing.JTextField txtIssueDate;
    private javax.swing.JTextField txtLastTradingDate;
    private javax.swing.JTextField txtTickSize;
    // End of variables declaration//GEN-END:variables

    private void postInit() {
        setUpCurrencyCombo();
        setUpDaycountCombo();
        setUpSettlementCombo();

        if (bean != null) {
            isInsert = false;
            txtIsin.setText(bean.getBondFutureMasterData().getIsin());
            txtIsin.setEditable(false);
            txtDescription.setText(bean.getBondFutureMasterData().getDescription());
            txtContractValue.setText(Converter.fromDouble(bean.getBondFutureMasterData().getContractValue()));
            txtTickSize.setText(Converter.fromDouble(bean.getBondFutureMasterData().getTickSize()));
            txtInitMargin.setText(Converter.fromDouble(bean.getBondFutureMasterData().getInitialMargin()));
            txtIssueDate.setText(new Date(bean.getBondFutureMasterData().getIssueDate()).toString());
            txtExpiryDate.setText(new Date(bean.getBondFutureMasterData().getMaturityDate()).toString());
            txtLastTradingDate.setText(new Date(bean.getBondFutureMasterData().getMaturityDate()).toString());
            txtContractCode.setText(bean.getBondFutureMasterData().getExchangeContractCode());
            cbCurrency.setSelectedItem(bean.getBondFutureMasterData().getCurrency());
            cbDaycount.setSelectedItem(bean.getBondFutureMasterData().getDaycount());
            cbSettlementType.setSelectedItem(bean.getBondFutureMasterData().getSettlementType());
        }

        // Aggiungo i campi alla lista di validazione
        fieldsToValidate = Arrays.asList(txtIsin, txtDescription, txtContractValue, txtTickSize,
                txtInitMargin, txtIssueDate, txtExpiryDate, txtLastTradingDate, txtContractCode);

    }

    private void setUpCurrencyCombo() {
        List<Currency> currencies = masterDataFacade.getCurrencyDAO().findAll();

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<Currency> model = new DefaultComboBoxModel<>(currencies.toArray(Currency[]::new));
        cbCurrency.setModel(model);
    }

    private void setUpDaycountCombo() {
        List<Daycount> daycounts = masterDataFacade.getDaycountDAO().findAll();

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<Daycount> model = new DefaultComboBoxModel<>(daycounts.toArray(Daycount[]::new));
        cbDaycount.setModel(model);
    }

    private void setUpSettlementCombo() {
        List<SettlementType> settlements = masterDataFacade.getSettlementTypeDAO().findAll();

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<SettlementType> model = new DefaultComboBoxModel<>(settlements.toArray(SettlementType[]::new));
        cbSettlementType.setModel(model);
    }

    // Check sulla validita dei campi, non devono essere blank
    private boolean validateFields() {
        return MDDialogHelper.validateFields(fieldsToValidate);
    }

    private boolean validateIntegrity() {
        if (isInsert) {
            // Controlla univocita codice ISIN
            String isin = txtIsin.getText();
            BondFutureMasterData bfmd = masterDataFacade.getBondFutureMasterDataDAO().findByIsin(isin);
            if (bfmd != null) {
                return false;
            }
        }

        // Controllo congruenza date
        Date issueDate = new Date(txtIssueDate.getText());
        Date expiryDate = new Date(txtExpiryDate.getText());
        Date lastTradingDate = new Date(txtLastTradingDate.getText());

        if (issueDate.isGreaterThan(expiryDate) || issueDate.isGreaterThan(lastTradingDate)) {
            return false;
        }

        if (lastTradingDate.isGreaterThan(expiryDate)) {
            return false;
        }

        return true;
    }

    private boolean saveBean() {

        try {
            if (isInsert) {
                bean = new FutBondBean(new BondFutureMasterData());
                fillDefaultFields();
            }
            BondFutureMasterData bfmd = bean.getBondFutureMasterData();
            bfmd.setIsin(txtIsin.getText());
            bfmd.setCode(txtIsin.getText());
            bfmd.setDescription(txtDescription.getText());
            bfmd.setContractValue(Converter.toDouble(txtContractValue.getText(), false));
            bfmd.setTickSize(Converter.toDouble(txtTickSize.getText(), false));
            bfmd.setInitialMargin(Converter.toDouble(txtInitMargin.getText(), false));
            bfmd.setExchangeContractCode(txtContractCode.getText());
            bfmd.setIssueDate(new Date(txtIssueDate.getText()).sqlDate());
            bfmd.setMaturityDate(new Date(txtExpiryDate.getText()).sqlDate());
            Currency currency = (Currency) cbCurrency.getSelectedItem();
            bfmd.setCurrency(currency);
            bfmd.setCalendar(currency.getCalendar());
            bfmd.setSettlementType((SettlementType) cbSettlementType.getSelectedItem());
            bfmd.setDaycount((Daycount) cbDaycount.getSelectedItem());
            masterDataFacade.getBondFutureMasterDataDAO().saveOrUpdate(bfmd);
            return true;
        } catch (Exception ex) {
            LoggerMgr.logError(ex.getLocalizedMessage());
            return false;
        }
    }

    private void fillDefaultFields() {
        // Aggiungo campi standard
        bean.getBondFutureMasterData().setTypeOfInterest(masterDataFacade.findTypeOfInterest("FIXED"));
        bean.getBondFutureMasterData().setForm(masterDataFacade.findForm("BEARER"));
        bean.getBondFutureMasterData().setFrequency(masterDataFacade.findFrequency("CUSTOM"));
        bean.getBondFutureMasterData().setRollConvention(masterDataFacade.findRollConvention("RC_NONE"));
        bean.getBondFutureMasterData().setAccrualScheduleType(100);
        bean.getBondFutureMasterData().setAssetClass(masterDataFacade.findAssetClass("BFU"));
        bean.getBondFutureMasterData().setAmortizationSchedule(masterDataFacade.findAmortizationSchedule("SAS"));

        bean.getBondFutureMasterData().setBusinessDays(2);
        bean.getBondFutureMasterData().setInterestRate(0.);
        bean.getBondFutureMasterData().setIssuePrice(100.);
        bean.getBondFutureMasterData().setRedempionPrice(100.);
    }
}
