/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.softcaster.master_data_mgr.dialogs;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.text.ParseException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ChangeEvent;
import org.softcaster.commons.types.Date;
import org.softcaster.commons.utils.Converter;
import org.softcaster.commons.utils.LoggerMgr;
import org.softcaster.core.data.CashFlowItem;
import org.softcaster.core.data.Currency;
import org.softcaster.core.data.Issuer;
import org.softcaster.core.data.SecurityMasterData;
import org.softcaster.engine.cashflow.BackwardScheduleGenerator;
import org.softcaster.engine.cashflow.BulletAmortizationStrategy;
import org.softcaster.engine.cashflow.CashFlow;
import org.softcaster.engine.cashflow.PaymentPeriod;
import org.softcaster.engine.enums.AccrualScheduleType;
import org.softcaster.engine.enums.AmortizationSchedule;
import org.softcaster.engine.enums.DaycountBasis;
import org.softcaster.engine.enums.Form;
import org.softcaster.engine.enums.Frequency;
import org.softcaster.engine.enums.RollConvention;
import org.softcaster.engine.enums.TypeOfInterest;
import org.softcaster.master_data_mgr.JMasterDataMgr;
import org.softcaster.master_data_mgr.MasterDataFacade;
import org.softcaster.master_data_mgr.models.MasterDataTableModel;
import org.softcaster.master_data_mgr.models.beans.CashFlowBean;
import org.softcaster.master_data_mgr.models.beans.SecurityBean;
import org.softcaster.master_data_mgr.ui.DecimalRenderer;
import org.softcaster.master_data_mgr.ui.ZebraTable;

/**
 *
 * @author ep
 */
public class BondDlg extends javax.swing.JDialog {

    private SecurityBean bean = null;
    private MasterDataFacade masterDataFacade = null;
    private List<javax.swing.JTextField> fieldsToValidate;
    private boolean isInsert = true;

    /**
     * Creates new form BondFutureDlg
     *
     * @param parent
     * @param modal
     * @param bean
     * @param masterDataFacade
     */
    public BondDlg(java.awt.Frame parent, boolean modal, SecurityBean bean, MasterDataFacade masterDataFacade) {
        super(parent, modal);
        this.bean = bean;
        this.masterDataFacade = masterDataFacade;
        initComponents();
        postInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        fieldPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIsin = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIssuePrice = new javax.swing.JTextField();
        txtRedempionPrice = new javax.swing.JTextField();
        txtCoupon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIssueDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtExpiryDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFirstCpMaturity = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jLabel13 = new javax.swing.JLabel();
        txtFirstCpRate = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtNominalValue = new javax.swing.JTextField();
        additionalPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbCurrency = new javax.swing.JComboBox<>();
        cbDaycount = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel12 = new javax.swing.JLabel();
        cbFrequency = new javax.swing.JComboBox<>();
        cbIssuer = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbRollConv = new javax.swing.JComboBox<>();
        cbForm = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbToi = new javax.swing.JComboBox<>();
        cbAmortSched = new javax.swing.JComboBox<>();
        codPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCfiCode = new javax.swing.JTextField();
        txtFisn = new javax.swing.JTextField();
        txtLei = new javax.swing.JTextField();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        cashFlowPanel = new javax.swing.JPanel();
        scrollPaneCF = new javax.swing.JScrollPane();
        tableCF = new ZebraTable();
        btnPanel = new javax.swing.JPanel();
        btnGenerateCF = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bond");
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        mainPanel.setLayout(new java.awt.GridBagLayout());

        fieldPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        fieldPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("ISIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtIsin, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtDescription, gridBagConstraints);

        jLabel3.setText("Issue Price");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Redempion Price");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel4, gridBagConstraints);

        txtIssuePrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIssuePrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIssuePriceFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtIssuePrice, gridBagConstraints);

        txtRedempionPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRedempionPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRedempionPriceFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtRedempionPrice, gridBagConstraints);

        txtCoupon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCoupon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCouponFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtCoupon, gridBagConstraints);

        jLabel5.setText("Coupon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Issue Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel6, gridBagConstraints);

        txtIssueDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIssueDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIssueDateFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtIssueDate, gridBagConstraints);

        jLabel7.setText("Maturity Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel7, gridBagConstraints);

        txtExpiryDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtExpiryDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtExpiryDateFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtExpiryDate, gridBagConstraints);

        jLabel8.setText("First Cp.Maturity");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel8, gridBagConstraints);
        jLabel8.getAccessibleContext().setAccessibleName("First C.Maturity");

        txtFirstCpMaturity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFirstCpMaturity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstCpMaturityFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtFirstCpMaturity, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        fieldPanel.add(filler1, gridBagConstraints);

        jLabel13.setText("First Cp. Rate");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel13, gridBagConstraints);

        txtFirstCpRate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFirstCpRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstCpRateFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtFirstCpRate, gridBagConstraints);

        jLabel21.setText("Nominal Value");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel21, gridBagConstraints);

        txtNominalValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNominalValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNominalValueFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtNominalValue, gridBagConstraints);

        tabbedPane.addTab("Specification", fieldPanel);

        additionalPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        additionalPanel.setLayout(new java.awt.GridBagLayout());

        jLabel9.setText("Issuer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Currency");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Daycount");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbCurrency, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbDaycount, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        additionalPanel.add(filler3, gridBagConstraints);

        jLabel12.setText("Frequency");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbFrequency, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbIssuer, gridBagConstraints);

        jLabel14.setText("Roll Conv.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel14, gridBagConstraints);

        jLabel15.setText("Form");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel15, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbRollConv, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbForm, gridBagConstraints);

        jLabel16.setText("Type Of Int.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel16, gridBagConstraints);

        jLabel17.setText("Amort. Sched.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel17, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbToi, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbAmortSched, gridBagConstraints);

        tabbedPane.addTab("Additional", additionalPanel);

        codPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        codPanel.setLayout(new java.awt.GridBagLayout());

        jLabel18.setText("Cfi Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        codPanel.add(jLabel18, gridBagConstraints);

        jLabel19.setText("Fisn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        codPanel.add(jLabel19, gridBagConstraints);

        jLabel20.setText("Lei");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        codPanel.add(jLabel20, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        codPanel.add(txtCfiCode, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        codPanel.add(txtFisn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        codPanel.add(txtLei, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        codPanel.add(filler4, gridBagConstraints);

        tabbedPane.addTab("Codification", codPanel);

        cashFlowPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        cashFlowPanel.setLayout(new java.awt.BorderLayout());

        tableCF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneCF.setViewportView(tableCF);

        cashFlowPanel.add(scrollPaneCF, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Cash Flows", cashFlowPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(tabbedPane, gridBagConstraints);

        btnPanel.setLayout(new java.awt.GridBagLayout());

        btnGenerateCF.setLabel("Generate CF");
        btnGenerateCF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateCFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        btnPanel.add(btnGenerateCF, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        btnPanel.add(filler2, gridBagConstraints);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(btnSave, gridBagConstraints);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(btnCancel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(btnPanel, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 605, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private boolean saveAction() {
        boolean isValid = validateFields() && validateIntegrity();

        if (!isValid) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please fill in all the required fields.", // Messaggio
                    "Validation Error", // Titolo
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!saveBean()) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error during save.\n See log file for more details.", // Messaggio
                    "Save Error", // Titolo
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (saveAction())
            this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtIssuePriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIssuePriceFocusLost
        MDDialogHelper.textFieldDoubleFocusLost(txtIssuePrice);
    }//GEN-LAST:event_txtIssuePriceFocusLost

    private void txtRedempionPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRedempionPriceFocusLost
        MDDialogHelper.textFieldDoubleFocusLost(txtRedempionPrice);
    }//GEN-LAST:event_txtRedempionPriceFocusLost

    private void txtCouponFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCouponFocusLost
        MDDialogHelper.textFieldDoubleFocusLost(txtCoupon);
    }//GEN-LAST:event_txtCouponFocusLost

    private void txtIssueDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIssueDateFocusLost
        MDDialogHelper.textFieldDateFocusLost(txtIssueDate);
    }//GEN-LAST:event_txtIssueDateFocusLost

    private void txtExpiryDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtExpiryDateFocusLost
        MDDialogHelper.textFieldDateFocusLost(txtExpiryDate);
    }//GEN-LAST:event_txtExpiryDateFocusLost

    private void txtFirstCpMaturityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstCpMaturityFocusLost
        MDDialogHelper.textFieldDateFocusLost(txtFirstCpMaturity);
    }//GEN-LAST:event_txtFirstCpMaturityFocusLost

    private void txtFirstCpRateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstCpRateFocusLost
        MDDialogHelper.textFieldDoubleFocusLost(txtFirstCpRate);
    }//GEN-LAST:event_txtFirstCpRateFocusLost

    private void txtNominalValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNominalValueFocusLost
        MDDialogHelper.textFieldDoubleFocusLost(txtNominalValue);
    }//GEN-LAST:event_txtNominalValueFocusLost

    private void btnGenerateCFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateCFActionPerformed

        boolean showMessage = bean != null
                && bean.getSecurityMasterData().getCashFlows() != null
                && !bean.getSecurityMasterData().getCashFlows().isEmpty();
        if (showMessage) {
            if (JOptionPane.showConfirmDialog(this,
                    "Cash Flows already present.\n Are you sure? ", JMasterDataMgr.TITLE,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION) {
            }
        } else {
            try {
                BackwardScheduleGenerator bsg = new BackwardScheduleGenerator();
                BulletAmortizationStrategy bas = new BulletAmortizationStrategy();
                LocalDate issueDate = new Date(txtIssueDate.getText()).sqlDate().toLocalDate();
                LocalDate maturityDate = new Date(txtExpiryDate.getText()).sqlDate().toLocalDate();
                List<PaymentPeriod> periods = bsg.generate(issueDate,
                        maturityDate,
                        org.softcaster.engine.enums.Frequency.SEMI_ANNUAL,
                        org.softcaster.engine.enums.BusinessDayConvention.FORWARD,
                        org.softcaster.engine.enums.DaycountBasis.ACT_ACT_ICMA,
                        null);

                double redemptionPrice;
                redemptionPrice = Converter.toDouble(txtRedempionPrice.getText(), false);
                double coupon;
                coupon = Converter.toDouble(txtCoupon.getText(), false);

                List<CashFlow> flows = bas.generateCashFlows(redemptionPrice, coupon * 0.01,
                        periods, org.softcaster.engine.enums.DaycountBasis.ACT_ACT_ICMA);

                List<CashFlowItem> items = new ArrayList<>();
                CashFlowItem item = null;
                for (CashFlow flow : flows) {
                    item = new CashFlowItem();
                    item.setStartDate(java.sql.Date.valueOf(flow.accrualStart()));
                    item.setEndDate(java.sql.Date.valueOf(flow.accrualEnd()));
                    item.setInterest(flow.interest());
                    item.setAmount(flow.principal());                    
                }
                MasterDataTableModel<CashFlowBean> model = (MasterDataTableModel<CashFlowBean>) tableCF.getModel();
                this.refreshModel(model, items);
            } catch (ParseException ex) {
                System.getLogger(BondDlg.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }

        }
    }//GEN-LAST:event_btnGenerateCFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel additionalPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGenerateCF;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel cashFlowPanel;
    private javax.swing.JComboBox<AmortizationSchedule> cbAmortSched;
    private javax.swing.JComboBox<Currency> cbCurrency;
    private javax.swing.JComboBox<DaycountBasis> cbDaycount;
    private javax.swing.JComboBox<Form> cbForm;
    private javax.swing.JComboBox<Frequency> cbFrequency;
    private javax.swing.JComboBox<Issuer> cbIssuer;
    private javax.swing.JComboBox<RollConvention> cbRollConv;
    private javax.swing.JComboBox<TypeOfInterest> cbToi;
    private javax.swing.JPanel codPanel;
    private javax.swing.JPanel fieldPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane scrollPaneCF;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tableCF;
    private javax.swing.JTextField txtCfiCode;
    private javax.swing.JTextField txtCoupon;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtExpiryDate;
    private javax.swing.JTextField txtFirstCpMaturity;
    private javax.swing.JTextField txtFirstCpRate;
    private javax.swing.JTextField txtFisn;
    private javax.swing.JTextField txtIsin;
    private javax.swing.JTextField txtIssueDate;
    private javax.swing.JTextField txtIssuePrice;
    private javax.swing.JTextField txtLei;
    private javax.swing.JTextField txtNominalValue;
    private javax.swing.JTextField txtRedempionPrice;
    // End of variables declaration//GEN-END:variables

    private void postInit() {

        setUpCombos();

        if (bean != null) {
            isInsert = false;
            txtIsin.setText(bean.getSecurityMasterData().getIsin());
            txtIsin.setEditable(false);
            txtDescription.setText(bean.getSecurityMasterData().getDescription());
            txtIssuePrice.setText(Converter.fromDouble(bean.getSecurityMasterData().getIssuePrice()));
            txtRedempionPrice.setText(Converter.fromDouble(bean.getSecurityMasterData().getRedempionPrice()));
            txtCoupon.setText(Converter.fromDouble(bean.getSecurityMasterData().getInterestRate()));
            txtIssueDate.setText(new Date(bean.getSecurityMasterData().getIssueDate()).toString());
            txtExpiryDate.setText(new Date(bean.getSecurityMasterData().getMaturityDate()).toString());
            txtFirstCpMaturity.setText(new Date(bean.getSecurityMasterData().getFirstCouponPaymentDate()).toString());
            txtFirstCpRate.setText(Converter.fromDouble(bean.getSecurityMasterData().getFirstCouponRate()));
            txtCfiCode.setText(bean.getSecurityMasterData().getCfiCode());
            txtFisn.setText(bean.getSecurityMasterData().getFisn());
            txtLei.setText(bean.getSecurityMasterData().getLei());
            cbIssuer.setSelectedItem(bean.getSecurityMasterData().getIssuer());
            cbCurrency.setSelectedItem(bean.getSecurityMasterData().getCurrency());
            cbDaycount.setSelectedItem(bean.getSecurityMasterData().getDaycount());
            cbFrequency.setSelectedItem(bean.getSecurityMasterData().getFrequency());
            cbRollConv.setSelectedItem(bean.getSecurityMasterData().getRollConvention());
            cbForm.setSelectedItem(bean.getSecurityMasterData().getForm());
            cbToi.setSelectedItem(bean.getSecurityMasterData().getTypeOfInterest());
            cbAmortSched.setSelectedItem(bean.getSecurityMasterData().getAmortizationSchedule());
            txtNominalValue.setText(Converter.fromDouble(bean.getSecurityMasterData().getNominalValue()));
        }

        // Aggiungo i campi alla lista di validazione
        fieldsToValidate = Arrays.asList(txtIsin, txtDescription, txtIssuePrice, txtRedempionPrice,
                txtCoupon, txtIssueDate, txtExpiryDate, txtFirstCpMaturity, txtFirstCpRate, txtNominalValue);

        initTable();

        // gestione bottone Generate CF
        btnGenerateCF.setVisible(false);
        tabbedPane.addChangeListener((ChangeEvent e) -> {
            Component panel = tabbedPane.getSelectedComponent();
            int index = tabbedPane.indexOfComponent(panel); // Trova l'indice del pannello
            if (index != -1) {
                String title1 = tabbedPane.getTitleAt(index); // Ottiene il testo del tab
                if (title1.equalsIgnoreCase("Cash Flows")) {
                    btnGenerateCF.setVisible(true);
                } else {
                    btnGenerateCF.setVisible(false);
                }
            }
        });
    }

    private void setUpCombos() {

        setUpCurrencyCombo();
        setUpDaycountCombo();
        setUpIssuerCombo();
        setUpFormCombo();
        setUpFrequencyCombo();
        setUpRollConvCombo();
        setUpToiCombo();
        setUpAmSchedCombo();
    }

    private void setUpToiCombo() {
        List<TypeOfInterest> tois = List.of(TypeOfInterest.values());

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<TypeOfInterest> model = new DefaultComboBoxModel<>(tois.toArray(TypeOfInterest[]::new));
        cbToi.setModel(model);
    }

    private void setUpAmSchedCombo() {
        List<AmortizationSchedule> amscheds = List.of(AmortizationSchedule.values());

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<AmortizationSchedule> model = new DefaultComboBoxModel<>(amscheds.toArray(AmortizationSchedule[]::new));
        cbAmortSched.setModel(model);
    }

    private void setUpFormCombo() {
        List<Form> forms = List.of(Form.values());

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<Form> model = new DefaultComboBoxModel<>(forms.toArray(Form[]::new));
        cbForm.setModel(model);
    }

    private void setUpFrequencyCombo() {
        List<Frequency> frequencies = List.of(Frequency.values());

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<Frequency> model = new DefaultComboBoxModel<>(frequencies.toArray(Frequency[]::new));
        cbFrequency.setModel(model);
    }

    private void setUpRollConvCombo() {
        List<RollConvention> rollconvs = List.of(RollConvention.values());

        // Crea il modello partendo dalla lista
        DefaultComboBoxModel<RollConvention> model = new DefaultComboBoxModel<>(rollconvs.toArray(RollConvention[]::new));
        cbRollConv.setModel(model);
    }

    private void setUpIssuerCombo() {
        List<Issuer> issuers = masterDataFacade.getIssuerDAO().findAll();

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<Issuer> model = new DefaultComboBoxModel<>(issuers.toArray(Issuer[]::new));
        cbIssuer.setModel(model);
    }

    private void setUpCurrencyCombo() {
        List<Currency> currencies = masterDataFacade.getCurrencyDAO().findAll();

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<Currency> model = new DefaultComboBoxModel<>(currencies.toArray(Currency[]::new));
        cbCurrency.setModel(model);
    }

    private void setUpDaycountCombo() {
        List<DaycountBasis> daycounts = List.of(DaycountBasis.values());

        // Crea il modello partendo dalla lista
        DefaultComboBoxModel<DaycountBasis> model = new DefaultComboBoxModel<>(daycounts.toArray(DaycountBasis[]::new));
        cbDaycount.setModel(model);
    }

    // Check sulla validita dei campi, non devono essere blank
    private boolean validateFields() {
        return MDDialogHelper.validateFields(fieldsToValidate);
    }

    private boolean validateIntegrity() {
        if (isInsert) {
            // Controlla univocita codice ISIN
            String isin = txtIsin.getText();
            SecurityMasterData smd = masterDataFacade.getSecurityMasterDataDAO().findByIsin(isin);
            if (smd != null) {
                return false;
            }
        }

        // Controllo congruenza date
        Date issueDate = new Date(txtIssueDate.getText());
        Date expiryDate = new Date(txtExpiryDate.getText());
        Date firstCpMaturity = new Date(txtFirstCpMaturity.getText());

        if (issueDate.isGreaterThan(expiryDate) || issueDate.isGreaterThan(firstCpMaturity)) {
            return false;
        }

        return !firstCpMaturity.isGreaterThan(expiryDate);
    }

    private boolean saveBean() {

        try {
            if (isInsert) {
                bean = new SecurityBean(new SecurityMasterData());
                fillDefaultFields();
            }
            SecurityMasterData smd = bean.getSecurityMasterData();

            smd.setIsin(txtIsin.getText());
            smd.setCode(txtIsin.getText());
            smd.setDescription(txtDescription.getText());
            smd.setIssuePrice(Converter.toDouble(txtIssuePrice.getText(), false));
            smd.setRedempionPrice(Converter.toDouble(txtRedempionPrice.getText(), false));
            smd.setInterestRate(Converter.toDouble(txtCoupon.getText(), false));
            smd.setIssueDate(new Date(txtIssueDate.getText()).sqlDate());
            smd.setMaturityDate(new Date(txtExpiryDate.getText()).sqlDate());
            Currency currency = (Currency) cbCurrency.getSelectedItem();
            smd.setCurrency(currency);
            smd.setDaycount((DaycountBasis) cbDaycount.getSelectedItem());
            smd.setAccrualDaycount(DaycountBasis.ACT_365);
            smd.setAccrualScheduleType(AccrualScheduleType.NONE);
            smd.setAmortizationSchedule((AmortizationSchedule) cbAmortSched.getSelectedItem());
            smd.setForm((Form) cbForm.getSelectedItem());
            smd.setFrequency((Frequency) cbFrequency.getSelectedItem());
            smd.setRollConvention((RollConvention) cbRollConv.getSelectedItem());
            smd.setTypeOfInterest((TypeOfInterest) cbToi.getSelectedItem());
            smd.setIssuer((Issuer) cbIssuer.getSelectedItem());
            smd.setNominalValue(Converter.toDouble(txtNominalValue.getText(), false));
            smd.setFirstCouponPaymentDate(new Date(txtFirstCpMaturity.getText()).sqlDate());
            smd.setFirstCouponRate(Converter.toDouble(txtFirstCpRate.getText(), false));
            smd.setCfiCode(txtCfiCode.getText());
            smd.setFisn(txtFisn.getText());
            smd.setLei(txtLei.getText());
            smd.setMultiplier(0.01);
            masterDataFacade.getSecurityMasterDataDAO().saveOrUpdate(smd);

            return true;
        } catch (Exception ex) {
            LoggerMgr.logError(ex.getLocalizedMessage());
            return false;
        }
    }

    private void fillDefaultFields() {
        // Aggiungo campi standard
        bean.getSecurityMasterData().setAssetClass(masterDataFacade.findAssetClass("XRB"));
        bean.getSecurityMasterData().setBusinessDays(2);
        if (txtCfiCode.getText().isBlank()) {
            bean.getSecurityMasterData().setCfiCode("");
        }
        if (txtFisn.getText().isBlank()) {
            bean.getSecurityMasterData().setFisn("");
        }
        if (txtLei.getText().isBlank()) {
            bean.getSecurityMasterData().setLei("");
        }
    }

    private void refreshModel(MasterDataTableModel model, List<CashFlowItem> items) {
        List<CashFlowBean> cfBeanList = new ArrayList<>();
        CashFlowBean cfb = null;
        for (CashFlowItem item : items) {
            cfb = new CashFlowBean(item);
            cfBeanList.add(cfb);
        }
        model.setData(cfBeanList);
    }

    protected void fillModelList() {
        // Crea e setta il model
        CashFlowBean prototype = new CashFlowBean(null);
        MasterDataTableModel<CashFlowBean> model = new MasterDataTableModel<>(prototype);
        tableCF.setModel(model);

        // Popola il model
        refreshModel(model, bean.getSecurityMasterData().getCashFlows());
    }

    protected void initTable() {
        tableCF.setFillsViewportHeight(true);
        tableCF.setRowHeight(25);
        tableCF.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));

        // Opzionale: Rimuovi le linee della griglia per un look più moderno (flat)
        tableCF.setShowGrid(false);
        tableCF.setIntercellSpacing(new Dimension(0, 0));

        // Header Elegante
        tableCF.getTableHeader().setOpaque(false);
        tableCF.getTableHeader().setBackground(new Color(230, 230, 230));
        tableCF.getTableHeader().setForeground(Color.BLACK);
        tableCF.getTableHeader().setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        // Più spazio rende i dati più leggibili
        tableCF.setRowHeight(30);

        // Selezione
        tableCF.setSelectionBackground(new Color(184, 207, 229)); // Un blu delicato per la riga selezionata
        tableCF.setSelectionForeground(Color.BLACK);

        tableCF.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableCF.setFocusable(false);
        tableCF.setRowSelectionAllowed(true);

        // Valido per tutti i campi double
        tableCF.setDefaultRenderer(Double.class, new DecimalRenderer());

        // Rendo la tabella sortabile
        tableCF.setAutoCreateRowSorter(true);

        // Setta il model e popola la tabella
        if (!isInsert) {
            fillModelList();
        }

    }

}
