/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.softcaster.master_data_mgr.dialogs;

import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.softcaster.commons.utils.LoggerMgr;
import org.softcaster.core.data.Counterparty;
import org.softcaster.core.data.CounterpartyType;
import org.softcaster.core.data.Country;
import org.softcaster.master_data_mgr.MasterDataFacade;
import org.softcaster.master_data_mgr.models.beans.CounterpartyBean;

/**
 *
 * @author ep
 */
public class CounterpartyDlg extends javax.swing.JDialog {

    private CounterpartyBean bean = null;
    private MasterDataFacade masterDataFacade = null;
    private List<javax.swing.JTextField> fieldsToValidate;
    private boolean isInsert = true;

    /**
     * Creates new form BondFutureDlg
     *
     * @param parent
     * @param modal
     * @param bean
     * @param masterDataFacade
     */
    public CounterpartyDlg(java.awt.Frame parent, boolean modal, CounterpartyBean bean, MasterDataFacade masterDataFacade) {
        super(parent, modal);
        this.bean = bean;
        this.masterDataFacade = masterDataFacade;
        initComponents();
        postInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        additionalPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbCountry = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cbNoe = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        txtCode = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtLeiCode = new javax.swing.JTextField();
        btnPanel = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bond Future");
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        mainPanel.setLayout(new java.awt.GridBagLayout());

        additionalPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        additionalPanel.setLayout(new java.awt.GridBagLayout());

        jLabel10.setText("Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel11, gridBagConstraints);

        jLabel12.setText("Country");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbCountry, gridBagConstraints);

        jLabel13.setText("Nature of Entity");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel13, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbNoe, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        additionalPanel.add(filler3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(txtCode, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(txtDescription, gridBagConstraints);

        jLabel14.setText("Lei Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel14, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(txtLeiCode, gridBagConstraints);

        tabbedPane.addTab("Specification", additionalPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(tabbedPane, gridBagConstraints);

        btnPanel.setLayout(new java.awt.GridBagLayout());

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(btnSave, gridBagConstraints);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(btnCancel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        btnPanel.add(filler2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(btnPanel, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 606, 307);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        boolean isValid = validateFields() && validateIntegrity();
        if (!isValid) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please check all the required fields.", // Messaggio
                    "Validation Error", // Titolo
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        } else {
            if (!saveBean()) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Error during save.\n See log file for more details.", // Messaggio
                        "Save Error", // Titolo
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel additionalPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Country> cbCountry;
    private javax.swing.JComboBox<CounterpartyType> cbNoe;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtLeiCode;
    // End of variables declaration//GEN-END:variables

    private void postInit() {
        setUpCountryCombo();
        setUpNoeCombo();

        if (bean != null) {
            isInsert = false;
            txtCode.setText(bean.getCounterparty().getCode());
            txtDescription.setText(bean.getCounterparty().getDescription());
            cbCountry.setSelectedItem(bean.getCounterparty().getCountry());
            cbNoe.setSelectedItem(bean.getCounterparty().getCtpType());
        }

        fieldsToValidate = Arrays.asList(txtCode, txtDescription);
    }

    private void setUpCountryCombo() {
        List<Country> countries = masterDataFacade.getCountryDAO().findAll();

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<Country> model = new DefaultComboBoxModel<>(countries.toArray(Country[]::new));
        cbCountry.setModel(model);
    }

    private void setUpNoeCombo() {
        List<CounterpartyType> types = masterDataFacade.getCounterpartyTypeDAO().findAll();

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<CounterpartyType> model = new DefaultComboBoxModel<>(types.toArray(CounterpartyType[]::new));
        cbNoe.setModel(model);
    }

    // Check sulla validita dei campi, non devono essere blank
    private boolean validateFields() {
        return MDDialogHelper.validateFields(fieldsToValidate);
    }

    private boolean validateIntegrity() {
        return true;
    }

    private boolean saveBean() {

        try {
            if (isInsert) {
                bean = new CounterpartyBean(new Counterparty());
                fillDefaultFields();
            }
            Counterparty ctp = bean.getCounterparty();
            ctp.setCode(txtCode.getText());
            ctp.setDescription(txtDescription.getText());
            ctp.setCountry((Country) cbCountry.getSelectedItem());
            ctp.setCtpType((CounterpartyType) cbNoe.getSelectedItem());
            ctp.setLeiCode(txtLeiCode.getText());
            masterDataFacade.getCounterpartyDAO().saveOrUpdate(ctp);
            return true;
        } catch (Exception ex) {
            LoggerMgr.logError(ex.getLocalizedMessage());
            return false;
        }
    }

    private void fillDefaultFields() {
        // Aggiungo campi standard
    }
}
