/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.softcaster.master_data_mgr.dialogs;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ListSelectionModel;
import org.softcaster.commons.ui.ZebraTable;
import org.softcaster.commons.utils.LoggerMgr;
import org.softcaster.core.data.BrokerInstrumentRules;
import org.softcaster.core.data.BrokerInstrumentRulesDAO;
import org.softcaster.core.data.Counterparty;
import org.softcaster.core.data.CounterpartyRoleMapping;
import org.softcaster.core.data.Country;
import org.softcaster.core.data.account.GlAccount;
import org.softcaster.engine.enums.CounterpartyRole;
import org.softcaster.engine.enums.CounterpartyType;
import org.softcaster.master_data_mgr.MasterDataFacade;
import org.softcaster.master_data_mgr.models.MasterDataTableModel;
import org.softcaster.master_data_mgr.models.beans.BrokerRuleBean;
import org.softcaster.master_data_mgr.models.beans.CounterpartyBean;
import org.softcaster.master_data_mgr.ui.DecimalRenderer;

/**
 *
 * @author ep
 */
public class CounterpartyDlg extends javax.swing.JDialog {

    private CounterpartyBean bean = null;
    private MasterDataFacade masterDataFacade = null;
    private List<javax.swing.JTextField> fieldsToValidate;
    private boolean isInsert = true;

    /**
     * Creates new form BondFutureDlg
     *
     * @param parent
     * @param modal
     * @param bean
     * @param masterDataFacade
     */
    public CounterpartyDlg(java.awt.Frame parent, boolean modal, CounterpartyBean bean, MasterDataFacade masterDataFacade) {
        super(parent, modal);
        this.bean = bean;
        this.masterDataFacade = masterDataFacade;
        initComponents();
        postInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        additionalPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbCountry = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cbNoe = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        txtCode = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtLeiCode = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbRoles = new javax.swing.JComboBox<>();
        rulesPanel = new javax.swing.JPanel();
        scrollPaneCF = new javax.swing.JScrollPane();
        tableRules = new ZebraTable();
        btnPanel = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bond Future");
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        mainPanel.setLayout(new java.awt.GridBagLayout());

        additionalPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        additionalPanel.setLayout(new java.awt.GridBagLayout());

        jLabel10.setText("Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel11, gridBagConstraints);

        jLabel12.setText("Country");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbCountry, gridBagConstraints);

        jLabel13.setText("Nature of Entity");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel13, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbNoe, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        additionalPanel.add(filler3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(txtCode, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(txtDescription, gridBagConstraints);

        jLabel14.setText("Lei Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel14, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(txtLeiCode, gridBagConstraints);

        jLabel15.setText("Roles");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel15, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbRoles, gridBagConstraints);

        tabbedPane.addTab("Detail", additionalPanel);

        rulesPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        rulesPanel.setLayout(new java.awt.BorderLayout());

        tableRules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneCF.setViewportView(tableRules);

        rulesPanel.add(scrollPaneCF, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Rules", rulesPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(tabbedPane, gridBagConstraints);

        btnPanel.setLayout(new java.awt.GridBagLayout());

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(btnSave, gridBagConstraints);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(btnCancel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        btnPanel.add(filler2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(btnPanel, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 606, 307);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        boolean isValid = validateFields() && validateIntegrity();
        if (!isValid) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please check all the required fields.", // Messaggio
                    "Validation Error", // Titolo
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        } else {
            if (!saveBean()) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Error during save.\n See log file for more details.", // Messaggio
                        "Save Error", // Titolo
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel additionalPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Country> cbCountry;
    private javax.swing.JComboBox<CounterpartyType> cbNoe;
    private javax.swing.JComboBox<CounterpartyRole> cbRoles;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel rulesPanel;
    private javax.swing.JScrollPane scrollPaneCF;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tableRules;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtLeiCode;
    // End of variables declaration//GEN-END:variables

    private void postInit() {
        setUpCountryCombo();
        setUpNoeCombo();
        setUpRolesCombo();

        if (bean != null) {
            isInsert = false;
            txtCode.setText(bean.getCounterparty().getCode());
            txtDescription.setText(bean.getCounterparty().getDescription());
            cbCountry.setSelectedItem(bean.getCounterparty().getCountry());
            cbNoe.setSelectedItem(bean.getCounterparty().getCtpType());
            txtLeiCode.setText(bean.getCounterparty().getLeiCode());
            if (bean.getCounterparty().getRoles() != null && !bean.getCounterparty().getRoles().isEmpty()) {
                CounterpartyRoleMapping mapping = bean.getCounterparty().getRoles().get(0);
                CounterpartyRole activeRole = mapping.getCtpRole();
                cbRoles.setSelectedItem(activeRole);
            }
        }

        fieldsToValidate = Arrays.asList(txtCode, txtDescription);
        initTable();
        
        GlAccount account = masterDataFacade.getGlAccountDAO().findByAccountId(30);
        System.out.println(account.getCode());
    }

    private void setUpCountryCombo() {
        List<Country> countries = masterDataFacade.getCountryDAO().findAll();
        // Crea il modello partendo dalla lista
        DefaultComboBoxModel<Country> model = new DefaultComboBoxModel<>(countries.toArray(Country[]::new));
        cbCountry.setModel(model);
    }

    private void setUpNoeCombo() {
        cbNoe.setRenderer(new IdentifiableEnumCellRenderer());
        List<CounterpartyType> types = List.of(CounterpartyType.values());

        // Crea il modello partendo dalla lista
        DefaultComboBoxModel<CounterpartyType> model = new DefaultComboBoxModel<>(types.toArray(CounterpartyType[]::new));
        cbNoe.setModel(model);
    }

    private void setUpRolesCombo() {
        cbRoles.setRenderer(new IdentifiableEnumCellRenderer());
        List<CounterpartyRole> types = List.of(CounterpartyRole.values());

        // Crea il modello partendo dalla lista
        DefaultComboBoxModel<CounterpartyRole> model = new DefaultComboBoxModel<>(types.toArray(CounterpartyRole[]::new));
        cbRoles.setModel(model);
    }

    // Check sulla validita dei campi, non devono essere blank
    private boolean validateFields() {
        return MDDialogHelper.validateFields(fieldsToValidate);
    }

    private boolean validateIntegrity() {
        return true;
    }

    private boolean saveBean() {

        try {
            if (isInsert) {
                bean = new CounterpartyBean(new Counterparty());
                fillDefaultFields();
            }
            Counterparty ctp = bean.getCounterparty();
            ctp.setCode(txtCode.getText());
            ctp.setDescription(txtDescription.getText());
            ctp.setCountry((Country) cbCountry.getSelectedItem());
            ctp.setCtpType((CounterpartyType) cbNoe.getSelectedItem());
            ctp.setLeiCode(txtLeiCode.getText());
            CounterpartyRole ctpRole = (CounterpartyRole) cbRoles.getSelectedItem();
            // Riottengo ctp appena salvata
            ctp = masterDataFacade.getCounterpartyDAO().saveOrUpdate(ctp);
            if (ctp != null && !ctp.hasRole(ctpRole)) {
                CounterpartyRoleMapping role = new CounterpartyRoleMapping();
                role.setCounterparty(ctp.getIdCounterparty());
                role.setCtpRole(ctpRole);
                ctp.getRoles().add(role);
                masterDataFacade.getCounterpartyDAO().saveOrUpdate(ctp);
            }

            return true;
        } catch (Exception ex) {
            LoggerMgr.logError(ex.getLocalizedMessage());
            return false;
        }
    }

    private void fillDefaultFields() {
        // Aggiungo campi standard
    }

    private void fillModelList() {
        // Crea e setta il model
        BrokerRuleBean prototype = new BrokerRuleBean(null);
        MasterDataTableModel<BrokerRuleBean> model = new MasterDataTableModel<>(prototype);
        tableRules.setModel(model);
        refreshModel(model);
    }

    private void refreshModel(MasterDataTableModel model) {
        List<BrokerRuleBean> rulesBeanList = new ArrayList<>();
        BrokerRuleBean ruleBean = null;
        if (bean.getCounterparty().getIdCounterparty() > 0) {
            BrokerInstrumentRulesDAO brokerInstrumentRulesDAO = masterDataFacade.getBrokerInstrumentRulesDAO();
            List<BrokerInstrumentRules> rules = brokerInstrumentRulesDAO.findByBroker(bean.getCounterparty().getIdCounterparty());
            if (rules != null && !rules.isEmpty()) {
                for (BrokerInstrumentRules rule : rules) {
                    ruleBean = new BrokerRuleBean(rule);
                    rulesBeanList.add(ruleBean);
                }
            }
        }
        model.setData(rulesBeanList);
    }

    protected void initTable() {
        tableRules.setFillsViewportHeight(true);
        tableRules.setRowHeight(25);
        tableRules.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));

        // Opzionale: Rimuovi le linee della griglia per un look più moderno (flat)
        tableRules.setShowGrid(false);
        tableRules.setIntercellSpacing(new Dimension(0, 0));

        // Header Elegante
        tableRules.getTableHeader().setOpaque(false);
        tableRules.getTableHeader().setBackground(new Color(230, 230, 230));
        tableRules.getTableHeader().setForeground(Color.BLACK);
        tableRules.getTableHeader().setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        // Più spazio rende i dati più leggibili
        tableRules.setRowHeight(30);

        // Selezione
        tableRules.setSelectionBackground(new Color(184, 207, 229)); // Un blu delicato per la riga selezionata
        tableRules.setSelectionForeground(Color.BLACK);

        tableRules.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableRules.setFocusable(false);
        tableRules.setRowSelectionAllowed(true);

        // Valido per tutti i campi double
        tableRules.setDefaultRenderer(Double.class, new DecimalRenderer());

        // Rendo la tabella sortabile
        tableRules.setAutoCreateRowSorter(true);

        // Setta il model e popola la tabella
        if (!isInsert) {
            fillModelList();
        }
    }
}
