/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.softcaster.master_data_mgr.dialogs;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.softcaster.commons.types.Date;
import org.softcaster.commons.utils.LoggerMgr;
import org.softcaster.core.data.Currency;
import org.softcaster.core.data.ForexMasterData;
import org.softcaster.core.data.YieldCurve;
import org.softcaster.master_data_mgr.MasterDataFacade;
import org.softcaster.master_data_mgr.models.beans.ForexBean;

/**
 *
 * @author ep
 */
public class CurrencyPairsDlg extends javax.swing.JDialog {

    private ForexBean bean = null;
    private MasterDataFacade masterDataFacade = null;
    private List<javax.swing.JTextField> fieldsToValidate;
    private boolean isInsert = true;

    /**
     * Creates new form BondFutureDlg
     *
     * @param parent
     * @param modal
     * @param bean
     * @param masterDataFacade
     */
    public CurrencyPairsDlg(java.awt.Frame parent, boolean modal, ForexBean bean, MasterDataFacade masterDataFacade) {
        super(parent, modal);
        this.bean = bean;
        this.masterDataFacade = masterDataFacade;
        initComponents();
        postInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        additionalPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbBcy = new javax.swing.JComboBox<>();
        cbCcy = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbBcyYC = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cbCcyYC = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnPanel = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bond Future");
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        mainPanel.setLayout(new java.awt.GridBagLayout());

        additionalPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        additionalPanel.setLayout(new java.awt.GridBagLayout());

        jLabel10.setText("Bcy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Ccy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbBcy, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbCcy, gridBagConstraints);

        jLabel12.setText("Bcy Y.Curve");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbBcyYC, gridBagConstraints);

        jLabel13.setText("Ccy Y.Curve");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel13, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbCcyYC, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        additionalPanel.add(filler3, gridBagConstraints);

        tabbedPane.addTab("Specification", additionalPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(tabbedPane, gridBagConstraints);

        btnPanel.setLayout(new java.awt.GridBagLayout());

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(btnSave, gridBagConstraints);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(btnCancel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        btnPanel.add(filler2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(btnPanel, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 606, 307);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        boolean isValid = validateFields() && validateIntegrity();
        if (!isValid) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please check all the required fields.", // Messaggio
                    "Validation Error", // Titolo
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        } else {
            if (!saveBean()) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Error during save.\n See log file for more details.", // Messaggio
                        "Save Error", // Titolo
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel additionalPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Currency> cbBcy;
    private javax.swing.JComboBox<YieldCurve> cbBcyYC;
    private javax.swing.JComboBox<Currency> cbCcy;
    private javax.swing.JComboBox<YieldCurve> cbCcyYC;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

    private void postInit() {
        setUpCurrencyCombo();
        setUpYieldCurveCombo();

        if (bean != null) {
            isInsert = false;
            cbBcy.setSelectedItem(bean.getForexMasterData().getCurrency());
            cbCcy.setSelectedItem(bean.getForexMasterData().getCcy());
            YieldCurve yc = masterDataFacade.getYieldCurveDAO().findByCode(bean.getForexMasterData().getBcyIrc());
            cbBcyYC.setSelectedItem(yc);
            yc = masterDataFacade.getYieldCurveDAO().findByCode(bean.getForexMasterData().getCcyIrc());
            cbCcyYC.setSelectedItem(yc);
        }
    }

    private void setUpCurrencyCombo() {
        List<Currency> currencies = masterDataFacade.getCurrencyDAO().findAll();

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<Currency> model = new DefaultComboBoxModel<>(currencies.toArray(Currency[]::new));
        cbBcy.setModel(model);

        model = new DefaultComboBoxModel<>(currencies.toArray(Currency[]::new));
        cbCcy.setModel(model);
    }

    private void setUpYieldCurveCombo() {
        List<YieldCurve> ycurves = masterDataFacade.getYieldCurveDAO().findAll();

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<YieldCurve> model = new DefaultComboBoxModel<>(ycurves.toArray(YieldCurve[]::new));
        cbBcyYC.setModel(model);

        model = new DefaultComboBoxModel<>(ycurves.toArray(YieldCurve[]::new));
        cbCcyYC.setModel(model);
    }

    // Check sulla validita dei campi, non devono essere blank
    private boolean validateFields() {
        return true;
    }

    private boolean validateIntegrity() {
        String bcy = ((Currency) cbBcy.getSelectedItem()).getIsoCode();
        String ccy = ((Currency) cbCcy.getSelectedItem()).getIsoCode();
        return !bcy.equalsIgnoreCase(ccy);
    }

    private boolean saveBean() {

        try {
            if (isInsert) {
                bean = new ForexBean(new ForexMasterData());
                fillDefaultFields();
            }
            ForexMasterData fmd = bean.getForexMasterData();
            fmd.setBcy((Currency) cbBcy.getSelectedItem());
            fmd.setCcy((Currency) cbCcy.getSelectedItem());
            fmd.setBcyIrc(((YieldCurve) cbBcyYC.getSelectedItem()).getCode());
            fmd.setCcyIrc(((YieldCurve) cbCcyYC.getSelectedItem()).getCode());
            masterDataFacade.getForexMasterDataDAO().saveOrUpdate(fmd);
            return true;
        } catch (Exception ex) {
            LoggerMgr.logError(ex.getLocalizedMessage());
            return false;
        }
    }

    private void fillDefaultFields() {
        // Aggiungo campi standard
        bean.getForexMasterData().setTypeOfInterest(masterDataFacade.findTypeOfInterest("FIXED"));
        bean.getForexMasterData().setForm(masterDataFacade.findForm("BEARER"));
        bean.getForexMasterData().setFrequency(masterDataFacade.findFrequency("NONE"));
        bean.getForexMasterData().setRollConvention(masterDataFacade.findRollConvention("UNADJUSTED"));
        bean.getForexMasterData().setAccrualScheduleType(100);
        bean.getForexMasterData().setAssetClass(masterDataFacade.findAssetClass("FSP"));
        bean.getForexMasterData().setAmortizationSchedule(masterDataFacade.findAmortizationSchedule("SAS"));

        bean.getForexMasterData().setBusinessDays(2);
        bean.getForexMasterData().setInterestRate(0.);
        bean.getForexMasterData().setIssuePrice(0.);
        bean.getForexMasterData().setRedempionPrice(0.);
        bean.getForexMasterData().setMultiplier(1.);

        // Dati relativi alla bcy
        Currency bcy = (Currency) cbBcy.getSelectedItem();
        bean.getForexMasterData().setCurrency(bcy);
        bean.getForexMasterData().setDaycount(bcy.getDaycount());
        Currency ccy = (Currency) cbCcy.getSelectedItem();
        bean.getForexMasterData().setAccrualDaycount(ccy.getDaycount());
        String code = bcy.getIsoCode()+ccy.getIsoCode();
        bean.getForexMasterData().setCode(code);
        bean.getForexMasterData().setIssueDate(new Date().sqlDate());
        bean.getForexMasterData().setMaturityDate(new Date().sqlDate());
    }
}
