/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.softcaster.master_data_mgr.dialogs;

import java.text.ParseException;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import org.softcaster.commons.types.Date;
import org.softcaster.commons.ui.dialog.DialogHelper;
import org.softcaster.commons.utils.Converter;
import org.softcaster.commons.utils.LoggerMgr;
import org.softcaster.core.data.Currency;
import org.softcaster.core.data.FxFutureMasterData;
import org.softcaster.core.data.PowerFutureMasterData;
import org.softcaster.engine.enums.SettlementType;
import org.softcaster.engine.enums.AccrualScheduleType;
import org.softcaster.engine.enums.AmortizationSchedule;
import org.softcaster.engine.enums.CommodityType;
import org.softcaster.engine.enums.Compounding;
import org.softcaster.engine.enums.DaycountBasis;
import org.softcaster.engine.enums.DeliveryPeriodType;
import org.softcaster.engine.enums.Form;
import org.softcaster.engine.enums.Frequency;
import org.softcaster.engine.enums.LoadType;
import org.softcaster.engine.enums.RollConvention;
import org.softcaster.engine.enums.TypeOfInterest;
import org.softcaster.master_data_mgr.MasterDataFacade;
import org.softcaster.master_data_mgr.models.beans.PowerFutBean;

/**
 *
 * @author ep
 */
public class ExtDeliveryFutureDlg extends javax.swing.JDialog {

    private PowerFutBean bean = null;
    private MasterDataFacade masterDataFacade = null;
    private List<javax.swing.JTextField> fieldsToValidate;
    private boolean isInsert = true;

    /**
     * Creates new form CmdFutureDlg
     *
     * @param parent
     * @param modal
     * @param bean
     * @param masterDataFacade
     */
    public ExtDeliveryFutureDlg(java.awt.Frame parent, boolean modal, PowerFutBean bean, MasterDataFacade masterDataFacade) {
        super(parent, modal);
        this.bean = bean;
        this.masterDataFacade = masterDataFacade;
        initComponents();
        postInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        fieldPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIsin = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtContractValue = new javax.swing.JTextField();
        txtTickSize = new javax.swing.JTextField();
        txtInitMargin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIssueDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtExpiryDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtLastTradingDate = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        additionalPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtContractCode = new javax.swing.JTextField();
        cbCurrency = new javax.swing.JComboBox<>();
        cbDaycount = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel12 = new javax.swing.JLabel();
        cbSettlementType = new javax.swing.JComboBox<>();
        cbUnderlying = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtMainMant = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        deliveryPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtDeliveryEnd = new javax.swing.JTextField();
        cbDeliveryPeriodType = new javax.swing.JComboBox<>();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNotionaMWH = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtDeliveryStart = new javax.swing.JTextField();
        spinnerDH = new javax.swing.JSpinner();
        txtNotionaMW = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cbLoadType = new javax.swing.JComboBox<>();
        btnPanel = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bond Future");
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        mainPanel.setLayout(new java.awt.GridBagLayout());

        fieldPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        fieldPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtIsin, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtDescription, gridBagConstraints);

        jLabel3.setText("Contract Value");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Tick Size");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel4, gridBagConstraints);

        txtContractValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtContractValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContractValueFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtContractValue, gridBagConstraints);

        txtTickSize.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTickSize.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTickSizeFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtTickSize, gridBagConstraints);

        txtInitMargin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtInitMargin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInitMarginFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtInitMargin, gridBagConstraints);

        jLabel5.setText("Initial Margin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Issue Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel6, gridBagConstraints);

        txtIssueDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIssueDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIssueDateFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtIssueDate, gridBagConstraints);

        jLabel7.setText("Expity Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel7, gridBagConstraints);

        txtExpiryDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtExpiryDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtExpiryDateFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtExpiryDate, gridBagConstraints);

        jLabel8.setText("Last Trading Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel8, gridBagConstraints);

        txtLastTradingDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLastTradingDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLastTradingDateFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtLastTradingDate, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        fieldPanel.add(filler1, gridBagConstraints);

        tabbedPane.addTab("Specification", fieldPanel);

        additionalPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        additionalPanel.setLayout(new java.awt.GridBagLayout());

        jLabel9.setText("Contract Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Currency");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Daycount");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(txtContractCode, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbCurrency, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbDaycount, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        additionalPanel.add(filler3, gridBagConstraints);

        jLabel12.setText("Settlement Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbSettlementType, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(cbUnderlying, gridBagConstraints);

        jLabel13.setText("Underlying");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel13, gridBagConstraints);

        txtMainMant.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMainMant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMainMantFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(txtMainMant, gridBagConstraints);

        jLabel14.setText("M. Margine");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        additionalPanel.add(jLabel14, gridBagConstraints);

        tabbedPane.addTab("Additional", additionalPanel);

        deliveryPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        deliveryPanel.setLayout(new java.awt.GridBagLayout());

        jLabel15.setText("Delivery Start");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        deliveryPanel.add(jLabel15, gridBagConstraints);

        jLabel16.setText("Delivery End");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        deliveryPanel.add(jLabel16, gridBagConstraints);

        jLabel17.setText("Delivery Period");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        deliveryPanel.add(jLabel17, gridBagConstraints);

        txtDeliveryEnd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDeliveryEnd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDeliveryEndFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        deliveryPanel.add(txtDeliveryEnd, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        deliveryPanel.add(cbDeliveryPeriodType, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        deliveryPanel.add(filler4, gridBagConstraints);

        jLabel18.setText("Delivery Hours");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        deliveryPanel.add(jLabel18, gridBagConstraints);

        jLabel19.setText("Notional MW");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        deliveryPanel.add(jLabel19, gridBagConstraints);

        txtNotionaMWH.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNotionaMWH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNotionaMWHFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        deliveryPanel.add(txtNotionaMWH, gridBagConstraints);

        jLabel20.setText("Notional MWh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        deliveryPanel.add(jLabel20, gridBagConstraints);

        txtDeliveryStart.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDeliveryStart.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDeliveryStartFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        deliveryPanel.add(txtDeliveryStart, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        deliveryPanel.add(spinnerDH, gridBagConstraints);

        txtNotionaMW.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNotionaMW.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNotionaMWFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        deliveryPanel.add(txtNotionaMW, gridBagConstraints);

        jLabel21.setText("Delivery Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        deliveryPanel.add(jLabel21, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        deliveryPanel.add(cbLoadType, gridBagConstraints);

        tabbedPane.addTab("Delivery", deliveryPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(tabbedPane, gridBagConstraints);

        btnPanel.setLayout(new java.awt.GridBagLayout());

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(btnSave, gridBagConstraints);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(btnCancel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        btnPanel.add(filler2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(btnPanel, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 606, 307);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        boolean isValid = validateFields() && validateIntegrity();
        if (!isValid) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please fill in all the required fields.", // Messaggio
                    "Validation Error", // Titolo
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        } else {
            if (!saveBean()) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Error during save.\n See log file for more details.", // Messaggio
                        "Save Error", // Titolo
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtContractValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContractValueFocusLost
        DialogHelper.textFieldDoubleFocusLost(txtContractValue);
    }//GEN-LAST:event_txtContractValueFocusLost

    private void txtTickSizeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTickSizeFocusLost
        try {
            double price = Converter.toDouble(txtTickSize.getText(), false);
            txtTickSize.setText(Converter.fromDouble(price));
        } catch (ParseException ex) {
            txtTickSize.setText("");
        }
    }//GEN-LAST:event_txtTickSizeFocusLost

    private void txtInitMarginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInitMarginFocusLost
        DialogHelper.textFieldDoubleFocusLost(txtInitMargin);
    }//GEN-LAST:event_txtInitMarginFocusLost

    private void txtIssueDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIssueDateFocusLost
        DialogHelper.textFieldDateFocusLost(txtIssueDate);
    }//GEN-LAST:event_txtIssueDateFocusLost

    private void txtExpiryDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtExpiryDateFocusLost
        DialogHelper.textFieldDateFocusLost(txtExpiryDate);
    }//GEN-LAST:event_txtExpiryDateFocusLost

    private void txtLastTradingDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastTradingDateFocusLost
        DialogHelper.textFieldDateFocusLost(txtLastTradingDate);
    }//GEN-LAST:event_txtLastTradingDateFocusLost

    private void txtMainMantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMainMantFocusLost
        DialogHelper.textFieldDoubleFocusLost(txtMainMant);
    }//GEN-LAST:event_txtMainMantFocusLost

    private void txtNotionaMWHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNotionaMWHFocusLost
        DialogHelper.textFieldDoubleFocusLost(txtNotionaMWH);
    }//GEN-LAST:event_txtNotionaMWHFocusLost

    private void txtNotionaMWFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNotionaMWFocusLost
        DialogHelper.textFieldDoubleFocusLost(txtNotionaMW);
    }//GEN-LAST:event_txtNotionaMWFocusLost

    private void txtDeliveryStartFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeliveryStartFocusLost

        DialogHelper.textFieldDateFocusLost(txtDeliveryStart);
    }//GEN-LAST:event_txtDeliveryStartFocusLost

    private void txtDeliveryEndFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeliveryEndFocusLost
        DialogHelper.textFieldDateFocusLost(txtDeliveryEnd);
    }//GEN-LAST:event_txtDeliveryEndFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel additionalPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Currency> cbCurrency;
    private javax.swing.JComboBox<DaycountBasis> cbDaycount;
    private javax.swing.JComboBox<DeliveryPeriodType> cbDeliveryPeriodType;
    private javax.swing.JComboBox<LoadType> cbLoadType;
    private javax.swing.JComboBox<SettlementType> cbSettlementType;
    private javax.swing.JComboBox<CommodityType> cbUnderlying;
    private javax.swing.JPanel deliveryPanel;
    private javax.swing.JPanel fieldPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JSpinner spinnerDH;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField txtContractCode;
    private javax.swing.JTextField txtContractValue;
    private javax.swing.JTextField txtDeliveryEnd;
    private javax.swing.JTextField txtDeliveryStart;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtExpiryDate;
    private javax.swing.JTextField txtInitMargin;
    private javax.swing.JTextField txtIsin;
    private javax.swing.JTextField txtIssueDate;
    private javax.swing.JTextField txtLastTradingDate;
    private javax.swing.JTextField txtMainMant;
    private javax.swing.JTextField txtNotionaMW;
    private javax.swing.JTextField txtNotionaMWH;
    private javax.swing.JTextField txtTickSize;
    // End of variables declaration//GEN-END:variables

    private void postInit() {
        setUpCurrencyCombo();
        setUpDaycountCombo();
        setUpSettlementCombo();
        setUpUnderlyingCombo();
        setUpDeliveryPeriodTypeCombo();
        setUpLoadTypeCombo();
        setUpSpinner();

        if (bean != null) {
            isInsert = false;
            txtIsin.setText(bean.getPowerFutureMasterData().getIsin());
            txtIsin.setEditable(false);
            txtDescription.setText(bean.getPowerFutureMasterData().getDescription());
            txtContractValue.setText(Converter.fromDouble(bean.getPowerFutureMasterData().getContractValue()));
            txtTickSize.setText(Converter.fromDouble(bean.getPowerFutureMasterData().getTickSize()));
            txtInitMargin.setText(Converter.fromDouble(bean.getPowerFutureMasterData().getInitialMargin()));
            txtIssueDate.setText(new Date(bean.getPowerFutureMasterData().getIssueDate()).toString());
            txtExpiryDate.setText(new Date(bean.getPowerFutureMasterData().getMaturityDate()).toString());
            txtLastTradingDate.setText(new Date(bean.getPowerFutureMasterData().getLastTradingDate()).toString());
            txtContractCode.setText(bean.getPowerFutureMasterData().getExchangeContractCode());
            cbCurrency.setSelectedItem(bean.getPowerFutureMasterData().getCurrency());
            cbDaycount.setSelectedItem(bean.getPowerFutureMasterData().getDaycount());
            cbSettlementType.setSelectedItem(bean.getPowerFutureMasterData().getSettlementType());
            txtMainMant.setText(Converter.fromDouble(bean.getPowerFutureMasterData().getMaintenanceMargin()));
            cbUnderlying.setSelectedItem(bean.getPowerFutureMasterData().getCommodityType());

            cbLoadType.setSelectedItem(bean.getPowerFutureMasterData().getLoadType());
            cbDeliveryPeriodType.setSelectedItem(bean.getPowerFutureMasterData().getDeliveryPeriodType());
            txtDeliveryStart.setText(new Date(bean.getPowerFutureMasterData().getDeliveryStart()).toString());
            txtDeliveryEnd.setText(new Date(bean.getPowerFutureMasterData().getDeliveryEnd()).toString());
            txtNotionaMW.setText(Converter.fromDouble(bean.getPowerFutureMasterData().getNotionalMw()));
            txtNotionaMWH.setText(Converter.fromDouble(bean.getPowerFutureMasterData().getNotionalMwh()));
            spinnerDH.setValue(bean.getPowerFutureMasterData().getTotalDeliveryHours());
        }

        // Aggiungo i campi alla lista di validazione
        fieldsToValidate = Arrays.asList(txtIsin, txtDescription, txtContractValue, txtTickSize,
                txtInitMargin, txtIssueDate, txtExpiryDate, txtLastTradingDate, txtContractCode, txtMainMant);

    }

    private void setUpCurrencyCombo() {
        List<Currency> currencies = masterDataFacade.getCurrencyDAO().findAll();

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<Currency> model = new DefaultComboBoxModel<>(currencies.toArray(Currency[]::new));
        cbCurrency.setModel(model);
    }

    private void setUpDaycountCombo() {
        List<DaycountBasis> daycounts = List.of(DaycountBasis.values());

        // Crea il modello partendo dalla lista
        DefaultComboBoxModel<DaycountBasis> model = new DefaultComboBoxModel<>(daycounts.toArray(DaycountBasis[]::new));
        cbDaycount.setModel(model);
    }

    private void setUpSettlementCombo() {
        List<SettlementType> types = List.of(SettlementType.values());

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<SettlementType> model = new DefaultComboBoxModel<>(types.toArray(SettlementType[]::new));
        cbSettlementType.setModel(model);
    }

    private void setUpUnderlyingCombo() {
        CommodityType[] commodities = CommodityType.values();
        DefaultComboBoxModel<CommodityType> model = new DefaultComboBoxModel<>(commodities);
        cbUnderlying.setModel(model);
    }

    // Check sulla validita dei campi, non devono essere blank
    private boolean validateFields() {
        return DialogHelper.validateFields(fieldsToValidate);
    }

    private boolean validateIntegrity() {
        if (isInsert) {
            // Controlla univocita codice ISIN
            String isin = txtIsin.getText();
            FxFutureMasterData ffmd = masterDataFacade.getFxFutureMasterDataDAO().findByCode(isin);
            if (ffmd != null) {
                return false;
            }
        }

        // Controllo congruenza date
        Date issueDate = new Date(txtIssueDate.getText());
        Date expiryDate = new Date(txtExpiryDate.getText());
        Date lastTradingDate = new Date(txtLastTradingDate.getText());

        if (issueDate.isGreaterThan(expiryDate) || issueDate.isGreaterThan(lastTradingDate)) {
            return false;
        }

        return !lastTradingDate.isGreaterThan(expiryDate);
    }

    private boolean saveBean() {

        try {
            if (isInsert) {
                bean = new PowerFutBean(new PowerFutureMasterData());
                fillDefaultFields();
            }
            PowerFutureMasterData ffmd = bean.getPowerFutureMasterData();
            ffmd.setIsin(txtIsin.getText());
            ffmd.setCode(txtIsin.getText());
            ffmd.setDescription(txtDescription.getText());
            ffmd.setContractValue(Converter.toDouble(txtContractValue.getText(), false));
            ffmd.setTickSize(Converter.toDouble(txtTickSize.getText(), false));
            ffmd.setInitialMargin(Converter.toDouble(txtInitMargin.getText(), false));
            ffmd.setExchangeContractCode(txtContractCode.getText());
            ffmd.setIssueDate(new Date(txtIssueDate.getText()).sqlDate());
            ffmd.setMaturityDate(new Date(txtExpiryDate.getText()).sqlDate());
            ffmd.setLastTradingDate(new Date(txtLastTradingDate.getText()).sqlDate());
            Currency currency = (Currency) cbCurrency.getSelectedItem();
            ffmd.setCurrency(currency);
            ffmd.setSettlementType((SettlementType) cbSettlementType.getSelectedItem());
            ffmd.setDaycount((DaycountBasis) cbDaycount.getSelectedItem());
            ffmd.setAccrualDaycount(DaycountBasis.ACT_360);
            ffmd.setCommodityType((CommodityType) cbUnderlying.getSelectedItem());
            ffmd.setMaintenanceMargin(Converter.toDouble(txtMainMant.getText(), false));
            ffmd.setLoadType((LoadType) cbLoadType.getSelectedItem());
            ffmd.setMarket("EEX");
            ffmd.setDeliveryPeriodType((DeliveryPeriodType) cbDeliveryPeriodType.getSelectedItem());
            ffmd.setDeliveryStart(new Date(txtDeliveryStart.getText()).sqlDate());
            ffmd.setDeliveryEnd(new Date(txtDeliveryEnd.getText()).sqlDate());
            ffmd.setNotionalMw(Converter.toDouble(txtNotionaMW.getText(), false));
            ffmd.setNotionalMwh(Converter.toDouble(txtNotionaMWH.getText(), false));
            ffmd.setTotalDeliveryHours((Integer) spinnerDH.getValue());
            masterDataFacade.getPowerFutureMasterDataDAO().saveOrUpdate(ffmd);
            return true;
        } catch (Exception ex) {
            LoggerMgr.logError(ex.getLocalizedMessage());
            return false;
        }
    }

    private void fillDefaultFields() {
        // Aggiungo campi standard
        bean.getPowerFutureMasterData().setTypeOfInterest(TypeOfInterest.NONE);
        bean.getPowerFutureMasterData().setForm(Form.BEARER);
        bean.getPowerFutureMasterData().setFrequency(Frequency.NONE);
        bean.getPowerFutureMasterData().setRollConvention(RollConvention.UNADJUSTED);
        bean.getPowerFutureMasterData().setAccrualScheduleType(AccrualScheduleType.NONE);
        bean.getPowerFutureMasterData().setAssetClass(masterDataFacade.findAssetClass("FFU"));
        bean.getPowerFutureMasterData().setAmortizationSchedule(AmortizationSchedule.NONE);

        bean.getPowerFutureMasterData().setBusinessDays(0);
        bean.getPowerFutureMasterData().setInterestRate(0.);
        bean.getPowerFutureMasterData().setIssuePrice(100.);
        bean.getPowerFutureMasterData().setRedempionPrice(100.);
        bean.getPowerFutureMasterData().setMultiplier(1.);
        bean.getPowerFutureMasterData().setCompounding(Compounding.COMPOUNDED);
    }

    private void setUpDeliveryPeriodTypeCombo() {
        List<DeliveryPeriodType> periods = List.of(DeliveryPeriodType.values());

        // Crea il modello partendo dalla lista
        DefaultComboBoxModel<DeliveryPeriodType> model = new DefaultComboBoxModel<>(periods.toArray(DeliveryPeriodType[]::new));
        cbDeliveryPeriodType.setModel(model);
    }

    private void setUpLoadTypeCombo() {
        List<LoadType> types = List.of(LoadType.values());

        // Crea il modello partendo dalla lista
        DefaultComboBoxModel<LoadType> model = new DefaultComboBoxModel<>(types.toArray(LoadType[]::new));
        cbLoadType.setModel(model);
    }

    private void setUpSpinner() {
        // Parametri del modello: valore iniziale (2), minimo (1), massimo (3), step (1)
        SpinnerNumberModel model = new SpinnerNumberModel(24, 1, 24, 1);
        spinnerDH.setModel(model);
        // Per bloccare l'editing da tastiera e costringere l'uso delle frecce (opzionale):
        JFormattedTextField txt = ((JSpinner.DefaultEditor) spinnerDH.getEditor()).getTextField();
        txt.setEditable(false);
    }
}
