/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.softcaster.easy_pricer_mds.dialog;

import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.softcaster.commons.ui.dialog.DialogHelper;
import org.softcaster.commons.utils.Converter;
import org.softcaster.commons.utils.LoggerMgr;
import org.softcaster.core.data.InstrumentQuote;
import org.softcaster.core.data.MasterData;
import org.softcaster.core.data.SecurityMasterData;
import org.softcaster.easy_pricer_mds.MDSFacade;
import org.softcaster.easy_pricer_mds.bean.BondBean;

/**
 *
 * @author ep
 */
public class BondIQDlg extends javax.swing.JDialog {

    /**
     * @return the confirmed
     */
    public boolean isConfirmed() {
        return confirmed;
    }

    private final MDSFacade mDSFacade;
    private BondBean bean;
    private boolean isInsert = true;
    private List<javax.swing.JTextField> fieldsToValidate;
    private boolean confirmed = false;

    /**
     * Creates new form CurrPairIQDlg
     *
     * @param parent
     * @param modal
     * @param bean
     * @param mDSFacade
     */
    public BondIQDlg(java.awt.Frame parent, boolean modal, BondBean bean, MDSFacade mDSFacade) {
        super(parent, modal);
        this.mDSFacade = mDSFacade;
        this.bean = bean;
        initComponents();
        postInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        detailPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBid = new javax.swing.JTextField();
        txtAsk = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        cbBond = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbProvider = new javax.swing.JComboBox<>();
        btnPanel = new javax.swing.JPanel();
        brnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        mainPanel.setLayout(new java.awt.GridBagLayout());

        detailPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Bond");
        jLabel1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        detailPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        detailPanel.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        detailPanel.add(txtCode, gridBagConstraints);

        jLabel3.setText("Bid");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        detailPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Ask");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        detailPanel.add(jLabel4, gridBagConstraints);

        txtBid.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBidFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        detailPanel.add(txtBid, gridBagConstraints);

        txtAsk.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAsk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAskFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        detailPanel.add(txtAsk, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        detailPanel.add(filler2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        detailPanel.add(cbBond, gridBagConstraints);

        jLabel5.setText("Provider");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        detailPanel.add(jLabel5, gridBagConstraints);

        cbProvider.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CmeGroupProvider", "EuroNextProvider", "InvestingComProvider" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        detailPanel.add(cbProvider, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(detailPanel, gridBagConstraints);

        btnPanel.setLayout(new java.awt.GridBagLayout());

        brnSave.setText("Save");
        brnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(brnSave, gridBagConstraints);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(btnCancel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        btnPanel.add(filler1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(btnPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        mainPanel.add(filler3, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 424, 252);
    }// </editor-fold>//GEN-END:initComponents

    private void brnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnSaveActionPerformed
        boolean isValid = validateFields() && validateIntegrity();

        if (!isValid) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please check all the required fields.", // Messaggio
                    "Validation Error", // Titolo
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        } else {
            if (!saveBean()) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Error during save.\n See log file for more details.", // Messaggio
                        "Save Error", // Titolo
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            confirmed = true;
            this.dispose();
        }

        this.dispose();
    }//GEN-LAST:event_brnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtBidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBidFocusLost
        DialogHelper.textFieldDoubleFocusLost(txtBid);
    }//GEN-LAST:event_txtBidFocusLost

    private void txtAskFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAskFocusLost
        DialogHelper.textFieldDoubleFocusLost(txtAsk);
    }//GEN-LAST:event_txtAskFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnSave;
    private javax.swing.JButton btnCancel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JComboBox<SecurityMasterData> cbBond;
    private javax.swing.JComboBox<String> cbProvider;
    private javax.swing.JPanel detailPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtAsk;
    private javax.swing.JTextField txtBid;
    private javax.swing.JTextField txtCode;
    // End of variables declaration//GEN-END:variables

    private void postInit() {
        setUpBondsCombo();

        if (bean != null) {
            isInsert = false;
            txtCode.setText(bean.getInstrumentQuote().getCode());
            cbBond.setSelectedItem(bean.getInstrumentQuote().getMasterData());
            txtBid.setText(Converter.fromDouble(bean.getBid()));
            txtAsk.setText(Converter.fromDouble(bean.getAsk()));
            cbProvider.setSelectedItem(bean.getInstrumentQuote().getProvider());
        } else {
            txtBid.setText(Converter.fromDouble(0.));
            txtAsk.setText(Converter.fromDouble(0.));
        }

        // Aggiungo i campi alla lista di validazione
        fieldsToValidate = Arrays.asList(txtCode, txtBid, txtAsk);

        // Aggiusto i campi
        txtCode.setColumns(10);
        txtBid.setColumns(10);
        txtAsk.setColumns(10);
    }

    private void setUpBondsCombo() {
        List<SecurityMasterData> bondList = mDSFacade.getSecurityMasterDataDAO().findAll();

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<SecurityMasterData> model = new DefaultComboBoxModel<>(bondList.toArray(SecurityMasterData[]::new));
        cbBond.setModel(model);

    }

    private boolean validateFields() {
        return DialogHelper.validateFields(fieldsToValidate);
    }

    private boolean validateIntegrity() {
        return true;
    }

    private boolean saveBean() {
        try {
            if (isInsert) {
                bean = new BondBean(new InstrumentQuote());
            }
            InstrumentQuote iq = bean.getInstrumentQuote();
            iq.setMasterData((MasterData) cbBond.getSelectedItem());
            iq.setCode(txtCode.getText());
            iq.setBid(Converter.toDouble(txtBid.getText(), false));
            iq.setAsk(Converter.toDouble(txtAsk.getText(), false));
            iq.setProvider(cbProvider.getSelectedItem().toString());
            mDSFacade.getInstrumentQuoteDAO().saveOrUpdate(iq);
            return true;
        } catch (Exception ex) {
            LoggerMgr.logError(ex.getLocalizedMessage());
            return false;
        }
    }
}
