/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.softcaster.easy_pricer_mds.dialog;

import java.sql.Date;
import java.text.ParseException;
import org.softcaster.commons.ui.dialog.DialogHelper;
import org.softcaster.commons.utils.Converter;
import org.softcaster.easy_pricer_mds.MDSFacade;
import org.softcaster.easy_pricer_mds.bean.BondBean;
import org.softcaster.easy_pricer_mds.bean.FltBondBean;
import org.softcaster.easy_pricer_mds_core.calc.BondCalculator;
import org.softcaster.easy_pricer_mds_core.dto.BondPricingRequest;
import org.softcaster.easy_pricer_mds_core.dto.BondPricingResponse;
import org.softcaster.engine.utils.DateParser;

/**
 *
 * @author ep
 */
public class BondPricerDlg extends javax.swing.JDialog {

    private final MDSFacade mDSFacade;
    private final BondBean bean;
    private final FltBondBean fltBean;

    /**
     * Creates new form BondPricerDlg
     *
     * @param parent
     * @param modal
     * @param bean
     * @param mDSFacade
     */
    public BondPricerDlg(java.awt.Frame parent, boolean modal, BondBean bean, MDSFacade mDSFacade) {
        super(parent, modal);
        this.bean = bean;
        this.fltBean = null;
        this.mDSFacade = mDSFacade;
        initComponents();
        postInit();
    }

    public BondPricerDlg(java.awt.Frame parent, boolean modal, FltBondBean bean, MDSFacade mDSFacade) {
        super(parent, modal);
        this.bean = null;
        this.fltBean = bean;
        this.mDSFacade = mDSFacade;
        initComponents();
        postInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        inputPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtISIN = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRefPrice = new javax.swing.JTextField();
        txtRefDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRefRate = new javax.swing.JTextField();
        resultPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAccrued = new javax.swing.JTextField();
        txtYield = new javax.swing.JTextField();
        txtModDuration = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDiscountMargin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtShortBondYield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMarginDuration = new javax.swing.JTextField();
        btnPanel = new javax.swing.JPanel();
        btnCalculate = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mainPanel.setLayout(new java.awt.GridBagLayout());

        inputPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("ISIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        inputPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Issue Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        inputPanel.add(jLabel2, gridBagConstraints);

        txtISIN.setEditable(false);
        txtISIN.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        inputPanel.add(txtISIN, gridBagConstraints);

        txtDescription.setEditable(false);
        txtDescription.setColumns(30);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        inputPanel.add(txtDescription, gridBagConstraints);

        jLabel3.setText("Reference Price");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        inputPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Reference Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        inputPanel.add(jLabel4, gridBagConstraints);

        txtRefPrice.setColumns(15);
        txtRefPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRefPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRefPriceFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        inputPanel.add(txtRefPrice, gridBagConstraints);

        txtRefDate.setColumns(15);
        txtRefDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRefDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRefDateFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        inputPanel.add(txtRefDate, gridBagConstraints);

        jLabel8.setText("Reference Rate(%)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        inputPanel.add(jLabel8, gridBagConstraints);

        txtRefRate.setColumns(15);
        txtRefRate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRefRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRefRateFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        inputPanel.add(txtRefRate, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(inputPanel, gridBagConstraints);

        resultPanel.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("Accrued Interest");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        resultPanel.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Yield to Maturity(%)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        resultPanel.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Modified Duration");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        resultPanel.add(jLabel7, gridBagConstraints);

        txtAccrued.setEditable(false);
        txtAccrued.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAccrued.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        resultPanel.add(txtAccrued, gridBagConstraints);

        txtYield.setEditable(false);
        txtYield.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtYield.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        resultPanel.add(txtYield, gridBagConstraints);

        txtModDuration.setEditable(false);
        txtModDuration.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtModDuration.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        resultPanel.add(txtModDuration, gridBagConstraints);

        jLabel9.setText("Discount Margin(%)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        resultPanel.add(jLabel9, gridBagConstraints);

        txtDiscountMargin.setEditable(false);
        txtDiscountMargin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDiscountMargin.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        resultPanel.add(txtDiscountMargin, gridBagConstraints);

        jLabel10.setText("Short Bond Yield(%)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        resultPanel.add(jLabel10, gridBagConstraints);

        txtShortBondYield.setEditable(false);
        txtShortBondYield.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtShortBondYield.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        resultPanel.add(txtShortBondYield, gridBagConstraints);

        jLabel11.setText("Margin Duration");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        resultPanel.add(jLabel11, gridBagConstraints);

        txtMarginDuration.setEditable(false);
        txtMarginDuration.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMarginDuration.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        resultPanel.add(txtMarginDuration, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(resultPanel, gridBagConstraints);

        btnPanel.setLayout(new java.awt.GridBagLayout());

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(btnCalculate, gridBagConstraints);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(btnExit, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        btnPanel.add(filler1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(btnPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(mainPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(filler2, gridBagConstraints);

        setBounds(0, 0, 586, 326);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        try {
            BondPricingRequest request = new BondPricingRequest();
            if (bean != null) {
                request.isin = bean.getInstrumentQuote().getMasterData().getCode();
            }
            if (fltBean != null) {
                request.isin = fltBean.getInstrumentQuote().getMasterData().getCode();
                request.referenceRate = Converter.toDouble(txtRefRate.getText(), false) / 100.;
            }
            request.referencePrice = Converter.toDouble(txtRefPrice.getText(), false);
            request.referenceDate = Date.valueOf(DateParser.parse(txtRefDate.getText()));

            BondCalculator calculator = mDSFacade.getBondCalculator();
            BondPricingResponse response = calculator.bondValuation(request);

            txtAccrued.setText(Converter.fromDouble(response.accruedInterest));
            txtYield.setText(Converter.fromDouble(response.yieldToMaturity * 100));
            txtModDuration.setText(Converter.fromDouble(response.modifiedDuration));
            if (fltBean != null) {
                txtDiscountMargin.setText(Converter.fromDouble(response.discountMargin * 100.));
                txtShortBondYield.setText(Converter.fromDouble(response.shortBondYield * 100.));
                txtMarginDuration.setText(Converter.fromDouble(response.marginDuration));
            } else {
                txtDiscountMargin.setText("");
                txtShortBondYield.setText("");
                txtMarginDuration.setText("");
            }

        } catch (ParseException ex) {
            System.getLogger(BondPricerDlg.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void txtRefDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRefDateFocusLost
        DialogHelper.textFieldDateFocusLost(txtRefDate);
    }//GEN-LAST:event_txtRefDateFocusLost

    private void txtRefPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRefPriceFocusLost
        DialogHelper.textFieldDoubleFocusLost(txtRefPrice);
    }//GEN-LAST:event_txtRefPriceFocusLost

    private void txtRefRateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRefRateFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefRateFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnExit;
    private javax.swing.JPanel btnPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JTextField txtAccrued;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtDiscountMargin;
    private javax.swing.JTextField txtISIN;
    private javax.swing.JTextField txtMarginDuration;
    private javax.swing.JTextField txtModDuration;
    private javax.swing.JTextField txtRefDate;
    private javax.swing.JTextField txtRefPrice;
    private javax.swing.JTextField txtRefRate;
    private javax.swing.JTextField txtShortBondYield;
    private javax.swing.JTextField txtYield;
    // End of variables declaration//GEN-END:variables

    private void postInit() {
        if (bean != null) {
            txtISIN.setText(bean.getInstrumentQuote().getMasterData().getCode());
            txtDescription.setText(bean.getInstrumentQuote().getMasterData().getDescription());
            txtRefRate.setEnabled(false);
        }
        if (fltBean != null) {
            txtISIN.setText(fltBean.getInstrumentQuote().getMasterData().getCode());
            txtDescription.setText(fltBean.getInstrumentQuote().getMasterData().getDescription());
        }
    }
}
