/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.softcaster.easy_pricer_mds.dialog;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import org.softcaster.commons.ui.DecimalRenderer;
import org.softcaster.commons.ui.ZebraTable;
import org.softcaster.easy_pricer_mds.MDSFacade;
import org.softcaster.easy_pricer_mds.bean.ODFBean;
import org.softcaster.easy_pricer_mds.bean.YieldCurveBean;
import org.softcaster.easy_pricer_mds.ui.model.YieldCurveRateModel;
import org.softcaster.easy_pricer_mds_core.MarketDataService;
import org.softcaster.engine.curve.OrderedDiscountFactor;

/**
 *
 * @author ep
 */
public final class YieldCurveDlg extends javax.swing.JDialog {

    private final List<ODFBean> oDFBeanList = new ArrayList<>();
    private MDSFacade mDSFacade = null;
    private final YieldCurveBean yieldCurveBean;

    /**
     * Creates new form YieldCurveDlg
     *
     * @param parent
     * @param modal
     * @param yieldCurveBean
     * @param mDSFacade
     */
    public YieldCurveDlg(java.awt.Frame parent, boolean modal, YieldCurveBean yieldCurveBean, MDSFacade mDSFacade) {
        super(parent, modal);
        this.yieldCurveBean = yieldCurveBean;
        this.mDSFacade = mDSFacade;
        initComponents();
        setTitle("Yield Curve: " + yieldCurveBean.getYieldCurve().getDescription());
        postInitComponents(ratesTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        detailPanel = new javax.swing.JPanel();
        ratesScrollPane = new javax.swing.JScrollPane();
        ratesTable = new ZebraTable();
        btnPanel = new javax.swing.JPanel();
        brnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        mainPanel.setLayout(new java.awt.GridBagLayout());

        detailPanel.setLayout(new java.awt.GridBagLayout());

        ratesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ratesScrollPane.setViewportView(ratesTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        detailPanel.add(ratesScrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(detailPanel, gridBagConstraints);

        btnPanel.setLayout(new java.awt.GridBagLayout());

        brnSave.setText("Save");
        brnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(brnSave, gridBagConstraints);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnPanel.add(btnCancel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        btnPanel.add(filler1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(btnPanel, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnSaveActionPerformed
        this.dispose();
    }//GEN-LAST:event_brnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnSave;
    private javax.swing.JButton btnCancel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JPanel detailPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane ratesScrollPane;
    private javax.swing.JTable ratesTable;
    // End of variables declaration//GEN-END:variables

    protected void postInitComponents(JTable table) {
        initTable(table);
    }
    
    private void fillModelList() {
        // Crea e setta il model
        ODFBean prototype = new ODFBean(null);
        YieldCurveRateModel model = new YieldCurveRateModel(prototype);
        ratesTable.setModel(model);

        oDFBeanList.clear();
        ODFBean bean = null;
        MarketDataService mds = mDSFacade.getMarketDataService();
        if (!yieldCurveBean.getYieldCurve().getProvider().isBlank()) {
            org.softcaster.engine.curve.YieldCurve yc = mds.getYieldCurve(yieldCurveBean.getYieldCurve().getCode());
            if (yc != null) {
                List<OrderedDiscountFactor> discounts = yc.getOrderedDiscountFactors();
                for (OrderedDiscountFactor odf : discounts) {
                    bean = new ODFBean(odf);
                    oDFBeanList.add(bean);
                }
            }
            model.setData(oDFBeanList);
        }
    }
    
    protected void initTable(JTable table) {
        table.setFillsViewportHeight(true);
        table.setRowHeight(25);
        table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));

        // Opzionale: Rimuovi le linee della griglia per un look più moderno (flat)
        table.setShowGrid(false);
        table.setIntercellSpacing(new Dimension(0, 0));

        // Header Elegante
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(new Color(230, 230, 230));
        table.getTableHeader().setForeground(Color.BLACK);
        table.getTableHeader().setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        // Più spazio rende i dati più leggibili
        table.setRowHeight(30);

        // Selezione
        table.setSelectionBackground(new Color(184, 207, 229)); // Un blu delicato per la riga selezionata
        table.setSelectionForeground(Color.BLACK);

        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        table.setFocusable(false);
        table.setRowSelectionAllowed(true);

        // Valido per tutti i campi double
        table.setDefaultRenderer(Double.class, new DecimalRenderer());

        // Rendo la tabella sortabile
        table.setAutoCreateRowSorter(true);

        // Setta il model e popola la tabella
        fillModelList();

        // 2. Forza il ricalcolo delle larghezze (IMPORTANTE: farlo dopo che la tabella ha i dati)
        java.awt.EventQueue.invokeLater(() -> {
            autoResizeColumns(table);
        });
    }
    
    protected void autoResizeColumns(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 50; // Larghezza minima iniziale

            // 1. Controlla la larghezza dell'Header
            TableCellRenderer headerRenderer = table.getTableHeader().getDefaultRenderer();
            Component headerComp = headerRenderer.getTableCellRendererComponent(table,
                    columnModel.getColumn(column).getHeaderValue(), false, false, 0, column);
            width = Math.max(headerComp.getPreferredSize().width + 20, width); // +20 per padding

            // 2. Controlla la larghezza dei dati (limita a un numero di righe se la tabella è enorme)
            for (int row = 0; row < Math.min(table.getRowCount(), 100); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + 20, width);
            }

            // Imposta la larghezza calcolata
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }
}
