/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softcaster.market_data_service.ui;

import java.awt.Color;
import java.util.Arrays;
import java.util.List;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.swing.text.TabSet;
import javax.swing.text.TabStop;
import org.softcaster.commons.utils.Converter;
import org.softcaster.commons.utils.LoggerMgr;
import org.softcaster.commons.xml.ParamsMgr;
import org.softcaster.market_data_service.IProgressInfo;
import org.softcaster.market_data_service.MarketDataService;
import static org.softcaster.market_data_service.ui.Instruments.CURRENCY_PAIRS;
import static org.softcaster.market_data_service.ui.Instruments.FUTURES;
import static org.softcaster.market_data_service.ui.Instruments.SECURITIES;

/**
 *
 * @author ep
 */
public class PricePanel extends javax.swing.JPanel implements IProgressInfo {

    // Definiamo gli stili
    Style blackStyle;
    Style blueStyle;

    /**
     * @return the instrument
     */
    public Instruments getInstrument() {
        return instrument;
    }

    /**
     * @param instrument the instrument to set
     */
    public void setInstrument(Instruments instrument) {
        this.instrument = instrument;
        updatePricePanelText();
        textArea.setText(null);
        setProgress(0);
    }

    private Instruments instrument = Instruments.CURRENCY_PAIRS;

    /**
     * Creates new form PricePanel
     */
    public PricePanel() {

        initComponents();
        updatePricePanelText();

        blackStyle = textArea.addStyle("Black", null);
        StyleConstants.setForeground(blackStyle, Color.BLACK);
        StyleConstants.setBold(blackStyle, true);

        blueStyle = textArea.addStyle("Blue", null);
        StyleConstants.setForeground(blueStyle, Color.BLUE);

        // 1. Definiamo dove deve iniziare la colonna dei numeri (es. 100 pixel)
        float posColNumbers = 150f;
        TabStop tabStop = new TabStop(posColNumbers, TabStop.ALIGN_RIGHT, TabStop.LEAD_NONE);
        TabSet tabSet = new TabSet(new TabStop[]{tabStop});

        // 2. Creiamo un set di attributi per il paragrafo e applichiamolo
        SimpleAttributeSet paragraphAttributes = new SimpleAttributeSet();
        StyleConstants.setTabSet(paragraphAttributes, tabSet);

        // Applica le impostazioni di tabulazione a tutto il JTextPane
        textArea.setParagraphAttributes(paragraphAttributes, false);
    }

    /**
     *
     */
    protected final void updatePricePanelText() {
        switch (instrument) {
            case CURRENCY_PAIRS ->
                lblInstrument.setText("Update Currency Pair");
            case FUTURES ->
                lblInstrument.setText("Update Futures");
            case SECURITIES ->
                lblInstrument.setText("Update Securities");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblInstrument = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextPane();

        setLayout(new java.awt.GridBagLayout());

        lblInstrument.setText("Instrument");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblInstrument, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(progressBar, gridBagConstraints);

        jScrollPane1.setViewportView(textArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInstrument;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextPane textArea;
    // End of variables declaration//GEN-END:variables

    public void update() {

        switch (instrument) {
            case CURRENCY_PAIRS ->
                updateFxPrice();
            case SECURITIES ->
                updateSecurityPrice();
        }
    }

    @Override
    public void setProgress(int progress) {
        progressBar.setValue(progress);
    }

    private void updateFxPrice() {
        MarketDataService mds = MarketDataService.getInstance();
        mds.updateFxPrice(this);

        // Leggo lista di currency pairs
        ParamsMgr paramsMgr = ParamsMgr.getInstance();
        String currencyPairs = paramsMgr.getParamValue("CURRENCY_PAIRS");

        // 1. Divido la stringa in un array usando la virgola come separatore
        String[] tokenArray = currencyPairs.split(",");
        // 2. Converto l'array in una List<String>
        List<String> tokenList = Arrays.asList(tokenArray);

        // Reset vecchia lettura
        textArea.setText(null);
        StyledDocument doc = textArea.getStyledDocument();
        for (String token : tokenList) {
            try {
                // Aggiungi EUR/USD in nero
                doc.insertString(doc.getLength(), token + "\t", blackStyle);
                // Aggiungi il valore in blu
                String price = Converter.fromDouble(mds.getSpotPrice(token));
                doc.insertString(doc.getLength(), price + "\n", blueStyle);
            } catch (BadLocationException ex) {
                LoggerMgr.logError(ex.getLocalizedMessage());
            }
        }
    }

    private void updateSecurityPrice() {
        MarketDataService mds = MarketDataService.getInstance();
        mds.updateSecurityPrice(this);

        // Leggo lista di currency pairs
        ParamsMgr paramsMgr = ParamsMgr.getInstance();
        String currencyPairs = paramsMgr.getParamValue("SECURITIES");

        // 1. Divido la stringa in un array usando la virgola come separatore
        String[] tokenArray = currencyPairs.split(",");
        // 2. Converto l'array in una List<String>
        List<String> tokenList = Arrays.asList(tokenArray);

        // Reset vecchia lettura
        textArea.setText(null);
        StyledDocument doc = textArea.getStyledDocument();
        for (String token : tokenList) {
            try {
                // Aggiungi EUR/USD in nero
                doc.insertString(doc.getLength(), token + "\t", blackStyle);
                // Aggiungi il valore in blu
                String price = Converter.fromDouble(mds.getSpotPrice(token));
                doc.insertString(doc.getLength(), price + "\n", blueStyle);
            } catch (BadLocationException ex) {
                LoggerMgr.logError(ex.getLocalizedMessage());
            }
        }
    }
}
