/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.softcaster.market_data_service;

import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.tree.DefaultMutableTreeNode;
import org.softcaster.commons.utils.LoggerMgr;
import org.softcaster.market_data_service.ui.Instruments;
import org.softcaster.marketdataprovider.MarketDataProviderHelper;

/**
 *
 * @author ep
 */
public class JMarketDataService extends javax.swing.JFrame {

    private static final String TITLE = "Market Data Service";
    private String currentCard = "HOME_PANEL"; // Valore iniziale

    /**
     * Creates new form JMarketDataService
     */
    public JMarketDataService() {
        initComponents();

        // Inizializzazione Logger
        MarketDataProviderHelper.initializeLogger();

        // Inizializzazione PythonPath da farsi prima di ogni utilizzo dell'interprete
        MarketDataProviderHelper.initializePython();

        // Titolo
        this.setTitle(TITLE);

        // Icona
        ImageIcon img = new ImageIcon(getClass().getResource("/images/favicon.png"));
        setIconImage(img.getImage());

        // Set the initial size of the window
        setSize(800, 600);

        // Finestra centrata nello schermo
        setLocationRelativeTo(null);

        // Impedisce a Swing di chiudere la finestra automaticamente
        setDefaultCloseOperation(javax.swing.JFrame.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                exitAction();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        sideNav = new javax.swing.JPanel();
        sideNavScrollPane = new javax.swing.JScrollPane();
        sideNavTree = new javax.swing.JTree();
        mainPanel = new javax.swing.JPanel();
        homePanel = new org.softcaster.market_data_service.ui.HomePanel();
        pricePanel = new org.softcaster.market_data_service.ui.PricePanel();
        yieldCurvePanel = new org.softcaster.market_data_service.ui.YieldCurvePanel();
        toolBar = new javax.swing.JToolBar();
        btnExit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        itemUpdate = new javax.swing.JMenuItem();
        itemSave = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        sideNav.setBackground(new java.awt.Color(204, 204, 204));
        sideNav.setPreferredSize(new java.awt.Dimension(200, 0));
        sideNav.setLayout(new java.awt.GridBagLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Navigation");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Home");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Price Update");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Currency Pairs");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Futures");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Securities");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Yield Curve");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Update");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Define");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        sideNavTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        sideNavTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                sideNavTreeValueChanged(evt);
            }
        });
        sideNavScrollPane.setViewportView(sideNavTree);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.ipady = 84;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        sideNav.add(sideNavScrollPane, gridBagConstraints);

        getContentPane().add(sideNav, java.awt.BorderLayout.WEST);

        mainPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(homePanel, "HOME_PANEL");
        mainPanel.add(pricePanel, "PRICE_PANEL");
        mainPanel.add(yieldCurvePanel, "YIELDCURVE_PANEL");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        toolBar.setRollover(true);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x-mark-2-16.png"))); // NOI18N
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        toolBar.add(btnExit);
        toolBar.add(jSeparator1);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gear-2-16-b.png"))); // NOI18N
        btnUpdate.setFocusable(false);
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        toolBar.add(btnUpdate);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save-16.png"))); // NOI18N
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnSave);

        getContentPane().add(toolBar, java.awt.BorderLayout.PAGE_START);

        menuFile.setText("File");

        itemUpdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gear-2-16-b.png"))); // NOI18N
        itemUpdate.setText("Update");
        itemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUpdateActionPerformed(evt);
            }
        });
        menuFile.add(itemUpdate);

        itemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save-16.png"))); // NOI18N
        itemSave.setText("Save");
        menuFile.add(itemSave);
        menuFile.add(jSeparator2);

        itemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x-mark-2-16.png"))); // NOI18N
        itemExit.setText("Exit");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        menuFile.add(itemExit);

        menuBar.add(menuFile);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        exitAction();
    }//GEN-LAST:event_itemExitActionPerformed

    private void sideNavTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_sideNavTreeValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) sideNavTree.getLastSelectedPathComponent();

        if (node == null) {
            return; // Nessuna selezione
        }
        // Converto il nodo in stringa (il nome visualizzato)
        String selectedNode = node.getUserObject().toString();

        // Recupero il CardLayout dal MainPanel
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        if (cl != null) {
            switch (selectedNode) {
                case "Home" ->
                    cl.show(mainPanel, "HOME_PANEL");
                case "Currency Pairs" -> {
                    pricePanel.setInstrument(Instruments.CURRENCY_PAIRS);
                    currentCard = "PRICE_PANEL";
                    cl.show(mainPanel, "PRICE_PANEL");
                }
                case "Futures" -> {
                    pricePanel.setInstrument(Instruments.FUTURES);
                    currentCard = "PRICE_PANEL";
                    cl.show(mainPanel, "PRICE_PANEL");
                }
                case "Securities" -> {
                    pricePanel.setInstrument(Instruments.SECURITIES);
                    currentCard = "PRICE_PANEL";
                    cl.show(mainPanel, "PRICE_PANEL");
                }
                case "Update" -> {
                    cl.show(mainPanel, "YIELDCURVE_PANEL");
                }
                default ->
                    cl.show(mainPanel, "HOME_PANEL");
                // Aggiungi gli altri casi...
                // Aggiungi gli altri casi...
            }
        }
    }//GEN-LAST:event_sideNavTreeValueChanged

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        exitAction();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updateAction();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void itemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUpdateActionPerformed
        // TODO add your handling code here:
        updateAction();
    }//GEN-LAST:event_itemUpdateActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JMarketDataService mainWnd = new JMarketDataService();
            mainWnd.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private org.softcaster.market_data_service.ui.HomePanel homePanel;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemSave;
    private javax.swing.JMenuItem itemUpdate;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private org.softcaster.market_data_service.ui.PricePanel pricePanel;
    private javax.swing.JPanel sideNav;
    private javax.swing.JScrollPane sideNavScrollPane;
    private javax.swing.JTree sideNavTree;
    private javax.swing.JToolBar toolBar;
    private org.softcaster.market_data_service.ui.YieldCurvePanel yieldCurvePanel;
    // End of variables declaration//GEN-END:variables

    private void exitAction() {
        if (JOptionPane.showConfirmDialog(this,
                "Are you sure?", TITLE,
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            LoggerMgr.logInfo("Bye bye!");
            System.exit(0);
        }
    }

    private void updateAction() {
        switch (currentCard) {
            case "HOME_PANEL" -> {
            }
            case "PRICE_PANEL" ->
                pricePanel.update();
            case "YIELDCURVE_PANEL" ->
                yieldCurvePanel.update();
        }
    }
}
