/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softcaster.easy_pricer_eod.ui.views;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.border.EmptyBorder;
import org.softcaster.commons.xml.ParamsMgr;
import org.softcaster.easy_pricer_eod.EODFacade;
import org.softcaster.easy_pricer_eod.services.RestServiceDescriptor;
import org.springframework.http.MediaType;
import org.springframework.web.client.RestClient;

/**
 *
 * @author ep
 */
public final class EodBatchPanel extends javax.swing.JPanel implements ServicePanel, ServiceInfo {

    private final List<RestServiceDescriptor> serviceDescriptorList = new ArrayList<>();
    private final EODFacade eodFacade;

    // Il modello che gestisce fisicamente i dati della lista
    private final DefaultListModel<String> listModel = new DefaultListModel<>();

    /**
     * Creates new form EodBatchPanel
     *
     * @param eodFacade
     */
    public EodBatchPanel(EODFacade eodFacade) {
        initComponents();
        this.eodFacade = eodFacade;
        messageList.setModel(listModel);
        messageList.setBorder(new EmptyBorder(10, 15, 10, 15));
        appendMessage("Eod Batch ready...");
        loadDescriptors();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        messageList = new javax.swing.JList<>();

        setLayout(new java.awt.BorderLayout(10, 10));

        messageList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPane.setViewportView(messageList);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void startService() {
        suspendAllServices();
    }

    @Override
    public void stopService() {
        System.out.println("stopService");
    }

    @Override
    public void suspendService() {
    }

    @Override
    public void restoreService() {
    }

    @Override
    public void refreshStatus() {
    }

    @Override
    public String getServiceName() {
        return null;
    }

    @Override
    public void clear() {
    }

    @Override
    public void logInfo(String info) {
    }

    @Override
    public void logError(String error) {
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> messageList;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

    public void appendMessage(String message) {
        // FONDAMENTALE: le modifiche all'interfaccia Swing devono avvenire nell'EDT
        java.awt.EventQueue.invokeLater(() -> {
            // Aggiunge l'elemento in fondo alla lista
            listModel.addElement(message);

            // OPZIONALE: Forza l'autoscroll per mostrare sempre l'ultimo messaggio inserito
            int lastIndex = listModel.getSize() - 1;
            if (lastIndex >= 0) {
                messageList.ensureIndexIsVisible(lastIndex);
            }
        });
    }

    private void suspendeService(RestServiceDescriptor descriptor) {
        // Eseguiamo la chiamata HTTP in un thread separato per evitare di bloccare l'interfaccia grafica Swing
        new Thread(() -> {
            try {
                appendMessage("Sending suspension request via HTTP to " + descriptor.getServiceName() + " service...");
                ParamsMgr paramsMgr = ParamsMgr.getInstance();
                String port = paramsMgr.getParamValue(descriptor.getServiceName() + "_PORT");
                RestClient restClient = RestClient.create();
                String baseUrl = "http://localhost:" + port + "/api/v1/internal/system/suspend";
                restClient.post()
                        .uri(baseUrl)
                        .accept(MediaType.APPLICATION_JSON)
                        .retrieve()
                        .toBodilessEntity(); // Invia la richiesta e attende la risposta (200 OK)

                appendMessage("Service " + descriptor.getServiceName() + " suspended successfully via HTTP.");

            } catch (Exception e) {
                // Gestione dell'errore se il server è già spento o irraggiungibile
                logError("HTTP suspension failed: " + e.getLocalizedMessage());
                appendMessage(e.getLocalizedMessage());

            }
        }).start();

    }

    private void suspendAllServices() {
        appendMessage("Suspend all services!");
        for (RestServiceDescriptor descriptor : serviceDescriptorList) {
            suspendeService(descriptor);
        }
    }

    private void loadService(String serviceName) {
        ParamsMgr paramsMgr = ParamsMgr.getInstance();
        String[] params = paramsMgr.getParamValue(serviceName).split(";");
        RestServiceDescriptor descriptor = new RestServiceDescriptor();
        descriptor.setServiceName(serviceName);
        descriptor.setJarPath(params[0]);
        descriptor.setActiveProfile(params[1]);
        descriptor.setServiceInfo(this);
        serviceDescriptorList.add(descriptor);
    }

    private void loadDescriptors() {
        loadService("RSRV");
        loadService("PSRV");
        loadService("MSRV");
        loadService("ASRV");
        loadService("LSRV");
    }
}
