/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softcaster.easy_pricer_eod.ui.views;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.softcaster.commons.types.Date;
import org.softcaster.commons.ui.dialog.DialogHelper;
import org.softcaster.core.data.Calendar;
import org.softcaster.core.data.Currency;
import org.softcaster.core.data.SystemBusinessCalendar;
import org.softcaster.easy_pricer_eod.EODFacade;
import org.softcaster.engine.enums.SbcStatus;

/**
 *
 * @author softc
 */
public class EodConfigPanel extends javax.swing.JPanel {

    private EODFacade eodFacade;
    private SystemBusinessCalendar sbc;

    /**
     * Creates new form EodConfigPanel
     *
     * @param eodFacade
     */
    public EodConfigPanel(EODFacade eodFacade) {
        initComponents();
        this.eodFacade = eodFacade;
        findBySbcId();
        setUpCombos();
        updateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fieldPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        cbCalendar = new javax.swing.JComboBox<>();
        cbCurrency = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLastOfficialDate = new javax.swing.JTextField();
        txtOfficialDate = new javax.swing.JTextField();
        nextOfficialDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        buttonsPanel = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        fieldPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Calendar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Currency");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtDescription, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(cbCalendar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(cbCurrency, gridBagConstraints);

        jLabel4.setText("Last Official Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Official Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Next Official Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel6, gridBagConstraints);

        txtLastOfficialDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtLastOfficialDate, gridBagConstraints);

        txtOfficialDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtOfficialDate, gridBagConstraints);

        nextOfficialDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        nextOfficialDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nextOfficialDateFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(nextOfficialDate, gridBagConstraints);

        jLabel7.setText("Status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(jLabel7, gridBagConstraints);

        txtStatus.setEditable(false);
        txtStatus.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtStatus, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(fieldPanel, gridBagConstraints);

        buttonsPanel.setLayout(new java.awt.GridBagLayout());

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        buttonsPanel.add(btnSave, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(buttonsPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        System.out.println("btnSaveActionPerformed");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void nextOfficialDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nextOfficialDateFocusLost
        DialogHelper.textFieldDateFocusLost(nextOfficialDate);
    }//GEN-LAST:event_nextOfficialDateFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JComboBox<Calendar> cbCalendar;
    private javax.swing.JComboBox<Currency> cbCurrency;
    private javax.swing.JPanel fieldPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nextOfficialDate;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtLastOfficialDate;
    private javax.swing.JTextField txtOfficialDate;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

    private void findBySbcId() {
        sbc = eodFacade.getSystemBusinessCalendarDAO().findBySbcId(1);
    }

    private void setUpCombos() {
        setUpCalendarCombo();
        setUpCurrencyCombo();
    }

    private void setUpCalendarCombo() {
        List<Calendar> calendars = eodFacade.getCalendarDAO().findAll();

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<Calendar> model = new DefaultComboBoxModel<>(calendars.toArray(Calendar[]::new));
        cbCalendar.setModel(model);

    }

    private void setUpCurrencyCombo() {
        List<Currency> currencies = eodFacade.getCurrencyDAO().findAll();

        // 2. Crea il modello partendo dalla lista
        DefaultComboBoxModel<Currency> model = new DefaultComboBoxModel<>(currencies.toArray(Currency[]::new));
        cbCurrency.setModel(model);

    }

    private void updateFields() {
        txtDescription.setText(sbc.getDescription());
        cbCurrency.setSelectedItem(sbc.getCurrency());
        cbCalendar.setSelectedItem(sbc.getCalendar());
        java.sql.Date sqlDate = java.sql.Date.valueOf(sbc.getLastOfficialDate());
        Date dt = new Date(sqlDate);
        txtLastOfficialDate.setText(dt.toString());
        sqlDate = java.sql.Date.valueOf(sbc.getOfficialDate());
        dt = new Date(sqlDate);
        txtOfficialDate.setText(dt.toString());
        if (sbc.getNextBusinessDate() != null) {
            sqlDate = java.sql.Date.valueOf(sbc.getNextBusinessDate());
            dt = new Date(sqlDate);
            nextOfficialDate.setText(dt.toString());
        }
        txtStatus.setText(sbc.getStatus().getDescription());
        if (sbc.getStatus() != SbcStatus.OPEN) {
            txtDescription.setEnabled(false);
            cbCurrency.setEnabled(false);
            cbCalendar.setEnabled(false);
            txtLastOfficialDate.setEnabled(false);
            txtOfficialDate.setEnabled(false);
            nextOfficialDate.setEnabled(false);
            btnSave.setEnabled(false);
        }
    }
}
