/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softcaster.easy_pricer_eod.ui.views;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import org.softcaster.commons.ui.ZebraTable;
import org.softcaster.commons.ui.model.FndtTableModel;
import org.softcaster.commons.ui.view.FndtAbstactPanel;
import org.softcaster.core.data.Descriptors;
import org.softcaster.easy_pricer_eod.EODFacade;
import org.softcaster.easy_pricer_eod.ui.models.DescriptorBean;
import org.softcaster.easy_pricer_eod.ui.models.DescriptorsTableModel;

/**
 *
 * @author ep
 */
public class MicroServicePanel extends FndtAbstactPanel {

    private final List<DescriptorBean> descriptorsList = new ArrayList<>();
    private final EODFacade eodFacade;
    /**
     * Creates new form MicroServicePanel
     * @param eodFacade
     */
    public MicroServicePanel(EODFacade eodFacade) {
        this.eodFacade = eodFacade;
        initComponents();
        postInitComponents(servicesTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        servicesTable = new ZebraTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout(10, 10));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(50, 50, 50));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Micro Services Setup");
        lblHeader.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblHeader, java.awt.BorderLayout.NORTH);
        lblHeader.getAccessibleContext().setAccessibleName("Micro Services Setup");
        lblHeader.getAccessibleContext().setAccessibleDescription("");

        servicesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPane.setViewportView(servicesTable);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void refreshAction() {
    }

    @Override
    protected void fillModelList() {
        // Crea e setta il model
        DescriptorBean prototype = new DescriptorBean(null);
        DescriptorsTableModel model = new DescriptorsTableModel(prototype);
        servicesTable.setModel(model);

        // Popola il model
        refreshModelFromDb(model);
    }

    protected void refreshModelFromDb(FndtTableModel ftm) {
        // Cancella vecchia lista
        descriptorsList.clear();

        // Leggo lista pairs anagrafiche
        List<Descriptors> descriptorList = eodFacade.getDescriptorsDAO().findAll();
        if (descriptorList.isEmpty()) {
            return;
        }

        DescriptorBean bean = null;
        for (Descriptors descriptor : descriptorList) {
            bean = new DescriptorBean(descriptor);
            descriptorsList.add(bean);
        }

        ftm.setData(descriptorsList);
    }

    @Override
    protected void refreshModel(FndtTableModel model) {
    }

    @Override
    protected void updateModel(FndtTableModel model) {
    }

    @Override
    protected void acNewActionPerformed(ActionEvent evt) {
    }

    @Override
    protected void acModActionPerformed(ActionEvent evt) {
        int rowIndex = servicesTable.getSelectedRow();
        if (rowIndex != -1) {
            // 1. CONVERSIONE FONDAMENTALE
            int modelRow = servicesTable.convertRowIndexToModel(rowIndex);
            DescriptorsTableModel model = (DescriptorsTableModel) servicesTable.getModel();
            DescriptorBean bean = model.getElementAt(modelRow);
            java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
            java.awt.Frame parentFrame = null;

            if (parentWindow instanceof java.awt.Frame frame) {
                parentFrame = frame;
            }

            ServiceSetupDlg dialog = new ServiceSetupDlg(parentFrame, true, bean, eodFacade);
            dialog.setSize(425, 250);
            // Centra la dialog rispetto al pannello
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

            // Post chiusura dialog
            if (dialog.isConfirmed()) {
                refreshModelFromDb(model);
            }
        }
    }

    @Override
    protected void acDelActionPerformed(ActionEvent evt) {
    }

    @Override
    public void downloadAction() {
    }

    @Override
    public void filterAction() {
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblHeader;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable servicesTable;
    // End of variables declaration//GEN-END:variables
}
