/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softcaster.easy_pricer_eod.ui.views;

import javax.swing.DefaultListModel;
import javax.swing.border.EmptyBorder;
import org.softcaster.commons.xml.ParamsMgr;
import org.softcaster.easy_pricer_eod.EODFacade;
import org.softcaster.easy_pricer_eod.services.RestServiceDescriptor;
import org.springframework.http.MediaType;
import org.springframework.web.client.RestClient;

/**
 *
 * @author softc
 */
public final class ProcEnginePanel extends javax.swing.JPanel implements ServicePanel, ServiceInfo {

    RestServiceDescriptor descriptor = null;
    EODFacade eodFacade;

    // Il modello che gestisce fisicamente i dati della lista
    private final DefaultListModel<String> listModel = new DefaultListModel<>();

    /**
     * Creates new form RestEnginePanel
     *
     * @param eodFacade
     */
    public ProcEnginePanel(EODFacade eodFacade) {
        initComponents();
        this.eodFacade = eodFacade;
        messageList.setModel(listModel);
        messageList.setBorder(new EmptyBorder(10, 15, 10, 15));
        loadServiceDescriptor();
        appendMessage("Processor Service ready...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        messageList = new javax.swing.JList<>();

        setLayout(new java.awt.BorderLayout(10, 10));

        messageList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPane.setViewportView(messageList);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> messageList;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo per appendere un nuovo messaggio di stato o log nella JList
     *
     * @param message
     */
    public void appendMessage(String message) {
        // FONDAMENTALE: le modifiche all'interfaccia Swing devono avvenire nell'EDT
        java.awt.EventQueue.invokeLater(() -> {
            // Aggiunge l'elemento in fondo alla lista
            listModel.addElement(message);

            // OPZIONALE: Forza l'autoscroll per mostrare sempre l'ultimo messaggio inserito
            int lastIndex = listModel.getSize() - 1;
            if (lastIndex >= 0) {
                messageList.ensureIndexIsVisible(lastIndex);
            }
        });
    }

    @Override
    public void startService() {
        appendMessage("Starting Processor service");
        eodFacade.getMicroserviceLauncher().startService(descriptor);
    }

    @Override
    public void stopService() {
        appendMessage("Closing Processor service");
        eodFacade.getMicroserviceLauncher().stopService(descriptor.getServiceName());
    }

    @Override
    public void refreshStatus() {
    }

    @Override
    public String getServiceName() {
        return "PSRV";
    }

    @Override
    public void clear() {
        listModel.clear();
    }

    private void loadServiceDescriptor() {
        ParamsMgr paramsMgr = ParamsMgr.getInstance();
        String[] params = paramsMgr.getParamValue("PSRV").split(";");
        descriptor = new RestServiceDescriptor();
        descriptor.setServiceName("PSRV");
        descriptor.setJarPath(params[0]);
        descriptor.setActiveProfile(params[1]);
        descriptor.setServiceInfo(this);
    }

    @Override
    public void logInfo(String info) {
        appendMessage("Info: " + info);
    }

    @Override
    public void logError(String error) {
        appendMessage("Error: " + error);
    }

    @Override
    public void suspendService() {
        appendMessage("Sending suspension request via HTTP to Processor service...");

        // Eseguiamo la chiamata HTTP in un thread separato per evitare di bloccare l'interfaccia grafica Swing
        new Thread(() -> {
            try {
                // 1. Istanzia il RestClient (funziona nativamente anche con web-application-type=none)
                RestClient restClient = RestClient.create();

                // 2. Ipotizziamo l'URL del microservizio REST (es. porta 8080)
                // Puoi anche recuperare la porta dinamicamente da ParamsMgr se configurata lì
                String baseUrl = "http://localhost:8081/api/v1/internal/system/suspend";

                // 3. Esegui la chiamata POST sincrona
                restClient.post()
                        .uri(baseUrl)
                        .accept(MediaType.APPLICATION_JSON)
                        .retrieve()
                        .toBodilessEntity(); // Invia la richiesta e attende la risposta (200 OK)

                appendMessage("Service suspended successfully via HTTP.");

            } catch (Exception e) {
                // Gestione dell'errore se il server è già spento o irraggiungibile
                logError("HTTP suspension failed: " + e.getLocalizedMessage());

                // Consiglio: se l'HTTP fallisce (es. server bloccato), proviamo comunque a killare il processo OS
                appendMessage("Force closing OS process due to HTTP failure...");
                eodFacade.getMicroserviceLauncher().stopService(descriptor.getServiceName());
            }
        }).start();
    }
}
