log4j.rootLogger=DEBUG,asrv

log4j.appender.asrv=org.apache.log4j.RollingFileAppender
log4j.appender.asrv.file=${user.dir}/log/msrv.log
log4j.appender.asrv.maxFileSize=10MB
log4j.appender.asrv.maxBackupIndex=10
log4j.appender.asrv.layout=org.apache.log4j.PatternLayout
log4j.appender.asrv.layout.ConversionPattern=%5p | %d | %m%n

log4j.logger.com.acme=DEBUG
log4j.logger.org.springframework=DEBUG
log4j.logger.javax.faces=DEBUG
log4j.logger.org.apache.myfaces=DEBUG
log4j.logger.com.sun.faces=DEBUG