
# Specifica che NON \u00e8 un'applicazione web (evita errori all'avvio)
spring.main.web-application-type=none

# Configurazione Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sofie
spring.datasource.username=sofie
spring.datasource.password=sofie
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurazione JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

# Configurazione Logging
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
