<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.3</version> <!-- Versione stabile corrente -->
        <relativePath/> 
    </parent>

    <groupId>org.softcaster.easy_import</groupId>
    <artifactId>easy_import</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <exec.mainClass>rg.softcaster.easy_import.EasyImport</exec.mainClass>
    </properties>

    <dependencies>
        <!-- Core Spring Boot -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- Database Relazionale (PostgreSQL) per Transazioni e Anagrafica -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.softcaster</groupId>
            <artifactId>easy_pricer_core</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>        
       
        <dependency>
            <groupId>org.softcaster.commons</groupId>
            <artifactId>foundation</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>ph.alephzero.finance</groupId>
            <artifactId>engine</artifactId>
            <version>1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>ph.alephzero</groupId>
                    <artifactId>foundation</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.softcaster.marketdataprovider</groupId>
            <artifactId>provider</artifactId>
            <version>1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.softcaster</groupId>
                    <artifactId>engine</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.softcaster</groupId>
                    <artifactId>foundation</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
    </dependencies>
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>*</include>
                </includes>
            </resource>
        </resources>
    </build>

</project>