<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.softcaster.easy_import</groupId>
    <artifactId>easy_import</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <exec.mainClass>rg.softcaster.easy_import.ImportMgr</exec.mainClass>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.7.4</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox -->
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>3.0.3</version>
        </dependency>
       
        <dependency>
            <groupId>org.softcaster.commons</groupId>
            <artifactId>foundation</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>ph.alephzero.finance</groupId>
            <artifactId>engine</artifactId>
            <version>1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>ph.alephzero</groupId>
                    <artifactId>foundation</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.softcaster.marketdataprovider</groupId>
            <artifactId>provider</artifactId>
            <version>1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.softcaster</groupId>
                    <artifactId>engine</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.softcaster</groupId>
                    <artifactId>foundation</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.20.1</version>
            <type>jar</type>
        </dependency>
    </dependencies>
    <build>
        <resources>
            <resource>
                <directory>src/main/resources/images</directory>
                <includes>
                    <include>*</include>
                </includes>
            </resource>
        </resources>
    </build>

</project>