/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.softcaster.easy_import;

import jakarta.annotation.PostConstruct;
import java.net.URL;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import org.softcaster.commons.utils.LoggerMgr;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author ep
 */
@Component
public final class ImportMgr extends javax.swing.JFrame implements IProgressInfo {

    static final private String imageLocation = System.getProperty("user.dir") + "//img//";

    // Spring riempie questa mappa usando il nome del @Service come chiave
    @Autowired
    private Map<String, IImportMgr> importers;

    private ImageIcon getIconImage(int icon) {
        ImageIcon image = null;
        switch (icon) {
            case 1 ->
                image = new ImageIcon(imageLocation + "x-mark-2-16.png");
            case 2 ->
                image = new ImageIcon(imageLocation + "gear-2-16-b.png");
            case 3 ->
                image = new ImageIcon(imageLocation + "trash-9-16.png");
            default -> {
            }
        }
        return image;
    }

    /**
     * Creates new form ImportMgr
     */
    public ImportMgr() {
        try {
            // Imposta il tema Windows
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            initComponents();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ImportMgr.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @PostConstruct
    public void init() {
        // Titolo
        this.setTitle("Import Manager");

        // Icona
        URL url = getClass().getResource("/images/favicon.png");
        if (url == null) {
            url = getClass().getResource("/resources/images/favicon.png");
        }
        //new ImageIcon(imageLocation +"gear-2-16-b").getImage();
        //new ImageIcon(imageLocation +"gear-2-16-b").getImage();
        ImageIcon img = new ImageIcon(imageLocation + "favicon.png");
        setIconImage(img.getImage());

        // Finestra centrata nello schermo
        setLocationRelativeTo(null);

        DefaultListModel<String> model = (DefaultListModel<String>) output.getModel();
        if (model != null) {

            // Popola la JComboBox automaticamente con i nomi degli importatori
            DefaultComboBoxModel<String> cbmodel = new DefaultComboBoxModel<>();
            for (String name : importers.keySet()) {
                cbmodel.addElement(name);
            }
            cmbImportMgr.setModel(cbmodel);
            cmbImportMgr.setSelectedIndex(-1);

            model.addElement("Select Importer");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cmbPanel = new javax.swing.JPanel();
        cmbImportMgr = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        toolBar = new javax.swing.JToolBar();
        btnExit = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnClear = new javax.swing.JButton();
        scrollPanel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        output = new JList(new DefaultListModel());
        progressBar = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuImport = new javax.swing.JMenuItem();
        mnuClear = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        cmbPanel.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        cmbPanel.add(cmbImportMgr, gridBagConstraints);

        jLabel1.setText("Importers");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        cmbPanel.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(cmbPanel, gridBagConstraints);

        toolBar.setRollover(true);

        btnExit.setIcon(getIconImage(1));
        btnExit.setToolTipText("Exit App.");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        toolBar.add(btnExit);

        btnImport.setIcon(getIconImage(2));
        btnImport.setToolTipText("Start Import");
        btnImport.setFocusable(false);
        btnImport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });
        toolBar.add(btnImport);
        toolBar.add(jSeparator1);

        btnClear.setIcon(getIconImage(3));
        btnClear.setToolTipText("Clear Log Window");
        btnClear.setFocusable(false);
        btnClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        toolBar.add(btnClear);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(toolBar, gridBagConstraints);

        scrollPanel.setLayout(new java.awt.GridBagLayout());

        scrollPane.setViewportView(output);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        scrollPanel.add(scrollPane, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        scrollPanel.add(progressBar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(scrollPanel, gridBagConstraints);

        jMenu1.setText("File");

        mnuImport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuImport.setIcon(getIconImage(2));
        mnuImport.setText("Import");
        mnuImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuImportActionPerformed(evt);
            }
        });
        jMenu1.add(mnuImport);

        mnuClear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuClear.setIcon(getIconImage(3));
        mnuClear.setText("Clear Log");
        mnuClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClearActionPerformed(evt);
            }
        });
        jMenu1.add(mnuClear);
        jMenu1.add(jSeparator2);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuExit.setIcon(getIconImage(1));
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuImportActionPerformed
        importAction();
    }//GEN-LAST:event_mnuImportActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        exitAction();
    }//GEN-LAST:event_mnuExitActionPerformed

    private IImportMgr getImportMgr(String importMgrName) {
        return importers.get(importMgrName);
    }

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        importAction();
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        exitAction();
    }//GEN-LAST:event_btnExitActionPerformed

    private void mnuClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClearActionPerformed
        clearAction();
    }//GEN-LAST:event_mnuClearActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearAction();
    }//GEN-LAST:event_btnClearActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        exitAction();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnImport;
    private javax.swing.JComboBox<String> cmbImportMgr;
    private javax.swing.JPanel cmbPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnuClear;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuImport;
    private javax.swing.JList<String> output;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel scrollPanel;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables

    ///////////////////////////////////////////////////////////////////////////////
// 
///////////////////////////////////////////////////////////////////////////////
    private void exitAction() {
        if (JOptionPane.showConfirmDialog(this,
                "Are you sure?", "Import Manager",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            LoggerMgr.logInfo("Bye bye!");
            System.exit(0);
        }
    }

    private void importAction() {
        String selectedName = (String) cmbImportMgr.getSelectedItem();
        IImportMgr importMgr = getImportMgr(selectedName);

        if (importMgr != null) {
            // 1. Preparazione UI (Thread sicuro perché siamo nell'evento del tasto)
            btnImport.setEnabled(false);
            progressBar.setValue(0);
            ((DefaultListModel<String>) output.getModel()).addElement("Import start: " + selectedName);

            // 2. Chiamata Asincrona (Spring sposta l'esecuzione nel pool di thread)
            // Passiamo 'this' perché il JFrame implementa IProgressInfo
            importMgr.start(this);

            // NOTA: La funzione finisce qui subito. Il lavoro continua "altrove".
        } else {
            ((DefaultListModel<String>) output.getModel()).addElement("No Importer selected!");
        }
    }

    private void clearAction() {
        DefaultListModel<String> model = (DefaultListModel<String>) output.getModel();
        if (model != null) {
            cmbImportMgr.setSelectedIndex(-1);
            model.removeAllElements();
            model.addElement("Select Importer");
            progressBar.setValue(0);
        }

    }

    @Override
    public void setProgress(int progress) {
        progressBar.setValue(progress);
    }

    @Override
    public void updateProgress(String message, int value) {
        // Cruciale: torniamo nel thread di Swing per aggiornare la grafica
        java.awt.EventQueue.invokeLater(() -> {
            progressBar.setValue(value);
            ((DefaultListModel<String>) output.getModel()).addElement(message);

            // Se il progresso è 100, riabilitiamo il tasto
            if (value >= 100) {
                btnImport.setEnabled(true);
            }
        });
    }

    @Override
    public void showError(String error) {
        java.awt.EventQueue.invokeLater(() -> {
            javax.swing.JOptionPane.showMessageDialog(this, error, "Errore", javax.swing.JOptionPane.ERROR_MESSAGE);
            btnImport.setEnabled(true); // Riabilita il tasto anche in caso di errore
        });
    }
}
