/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.softcaster.easy_import;

import java.io.File;
import java.lang.reflect.Method;
import java.net.URI;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.Properties;
import java.util.Vector;
import java.util.concurrent.ExecutionException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.SwingWorker;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import org.python.util.PythonInterpreter;
import org.softcaster.commons.utils.LoggerMgr;

/**
 *
 * @author ep
 */
public class ImportMgr extends javax.swing.JFrame implements IProgressInfo {

    static final private String imageLocation = System.getProperty("user.dir") + "//img//";

    static public void addPath(String s) throws Exception {
        File f = new File(s);
        URI uri = f.toURI();
        URL url = uri.toURL();
        URLClassLoader ucl = new URLClassLoader(new URL[]{url});
        Class urlClass = URLClassLoader.class;
        Method method = urlClass.getDeclaredMethod("addURL", new Class[]{URL.class});
        method.setAccessible(true);
        method.invoke(ucl, new Object[]{url});
    }

    private ImageIcon getIconImage(int icon) {
        ImageIcon image = null;
        switch (icon) {
            case 1 ->
                image = new ImageIcon(imageLocation + "x-mark-2-16.png");
            case 2 ->
                image = new ImageIcon(imageLocation + "gear-2-16-b.png");
            case 3 ->
                image = new ImageIcon(imageLocation + "trash-9-16.png");
            default -> {
            }
        }
        return image;
    }

    /**
     * Creates new form ImportMgr
     */
    public ImportMgr() {
        initComponents();

        // Titolo
        this.setTitle("Import Manager");

        // Icona
        URL url = getClass().getResource("/images/favicon.png");
        if (url == null) {
            url = getClass().getResource("/resources/images/favicon.png");
        }
        //new ImageIcon(imageLocation +"gear-2-16-b").getImage();
        //new ImageIcon(imageLocation +"gear-2-16-b").getImage();
        ImageIcon img = new ImageIcon(imageLocation + "favicon.png");
        setIconImage(img.getImage());

        // Finestra centrata nello schermo
        setLocationRelativeTo(null);

        DefaultListModel<String> model = (DefaultListModel<String>) output.getModel();
        if (model != null) {
            Vector<String> importers = new Vector<>();
            importers.add("Currencies");
            importers.add("Countries");
            importers.add("Bonds");
            importers.add("Cash Flows");
            importers.add("Yield Curves");
            importers.add("Btp Mini Futures");
            importers.add("Deliverable Bonds");
            importers.add("Instrument quotes");
            importers.add("Currency Pairs");
            cmbImportMgr.setModel(new DefaultComboBoxModel<>(importers));
            cmbImportMgr.setSelectedIndex(-1);
            model.addElement("Select Importer");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cmbPanel = new javax.swing.JPanel();
        cmbImportMgr = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        toolBar = new javax.swing.JToolBar();
        btnExit = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnClear = new javax.swing.JButton();
        scrollPanel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        output = new JList(new DefaultListModel());
        progressBar = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuImport = new javax.swing.JMenuItem();
        mnuClear = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        cmbPanel.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        cmbPanel.add(cmbImportMgr, gridBagConstraints);

        jLabel1.setText("Importers");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        cmbPanel.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(cmbPanel, gridBagConstraints);

        toolBar.setRollover(true);

        btnExit.setIcon(getIconImage(1));
        btnExit.setToolTipText("Exit App.");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        toolBar.add(btnExit);

        btnImport.setIcon(getIconImage(2));
        btnImport.setToolTipText("Start Import");
        btnImport.setFocusable(false);
        btnImport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });
        toolBar.add(btnImport);
        toolBar.add(jSeparator1);

        btnClear.setIcon(getIconImage(3));
        btnClear.setToolTipText("Clear Log Window");
        btnClear.setFocusable(false);
        btnClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        toolBar.add(btnClear);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(toolBar, gridBagConstraints);

        scrollPanel.setLayout(new java.awt.GridBagLayout());

        scrollPane.setViewportView(output);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        scrollPanel.add(scrollPane, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        scrollPanel.add(progressBar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(scrollPanel, gridBagConstraints);

        jMenu1.setText("File");

        mnuImport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuImport.setIcon(getIconImage(2));
        mnuImport.setText("Import");
        mnuImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuImportActionPerformed(evt);
            }
        });
        jMenu1.add(mnuImport);

        mnuClear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuClear.setIcon(getIconImage(3));
        mnuClear.setText("Clear Log");
        mnuClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClearActionPerformed(evt);
            }
        });
        jMenu1.add(mnuClear);
        jMenu1.add(jSeparator2);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuExit.setIcon(getIconImage(1));
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuImportActionPerformed
        importAction();
    }//GEN-LAST:event_mnuImportActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        exitAction();
    }//GEN-LAST:event_mnuExitActionPerformed

    private static IImportMgr getImportMgr(String importMgrName) {
        IImportMgr importMgr = null;
        if (importMgrName != null) {
            switch (importMgrName) {
                case "Currencies" ->
                    importMgr = CurrencyImportMgr.getInstance();
                case "Countries" ->
                    importMgr = CountryImportMgr.getInstance();
                case "Bonds" ->
                    importMgr = SecurityImportMgr.getInstance();
                case "Cash Flows" ->
                    importMgr = CashFlowImportMgr.getInstance();
                case "Yield Curves" ->
                    importMgr = YieldCurveImportMgr.getInstance();
                case "Btp Mini Futures" ->
                    importMgr = BondFutImportMgr.getInstance();
                case "Deliverable Bonds" ->
                    importMgr = DeliverableBondsImportMgr.getInstance();
                case "Instrument quotes" ->
                    importMgr = InstrumentQuoteImportMgr.getInstance();
                case "Currency Pairs" ->
                    importMgr = ForexImportMgr.getInstance();               
                default -> {
                }
            }
        }

        return importMgr;
    }

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        importAction();
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        exitAction();
    }//GEN-LAST:event_btnExitActionPerformed

    private void mnuClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClearActionPerformed
        clearAction();
    }//GEN-LAST:event_mnuClearActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearAction();
    }//GEN-LAST:event_btnClearActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        exitAction();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException, Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportMgr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        File conf = new File(System.getProperty("user.dir")
                + "//conf//log4j.conf");
        System.setProperty("log4j.configuration", "file:" + conf);

        // Inizializzazione PythonPath da farsi prima di ogni utilizzo dell'interprete
        String pythonPath = System.getProperty("user.dir") + "\\scripts";
        Properties props = new Properties();
        props.setProperty("python.path", pythonPath);
        PythonInterpreter.initialize(System.getProperties(), props, new String[]{""});

        /* Create and display the form */
        //addPath(imageLocation);
        javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ImportMgr().setVisible(true);

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnImport;
    private javax.swing.JComboBox<String> cmbImportMgr;
    private javax.swing.JPanel cmbPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnuClear;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuImport;
    private javax.swing.JList<String> output;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel scrollPanel;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables

    ///////////////////////////////////////////////////////////////////////////////
// 
///////////////////////////////////////////////////////////////////////////////
    private void exitAction() {
        if (JOptionPane.showConfirmDialog(this,
                "Are you sure?", "Import Manager",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            LoggerMgr.logInfo("Bye bye!");
            System.exit(0);
        }
    }

    private void importAction() {
        IProgressInfo progressInfo = this;
        // All code inside SwingWorker runs on a seperate thread
        SwingWorker<Boolean, Void> worker = new SwingWorker<Boolean, Void>() {
            DefaultListModel<String> model = (DefaultListModel<String>) output.getModel();

            @Override
            public Boolean doInBackground() {
                IImportMgr importMgr = getImportMgr((String) cmbImportMgr.getSelectedItem());
                if (importMgr != null) {
                    model.addElement("Import start!");
                    progressBar.setValue(0);
                    importMgr.start(progressInfo);
                } else {
                    model.addElement("No Importer selected!");
                }
                return true;
            }

            @Override
            public void done() {
                boolean status;
                try {
                    progressBar.setValue(100);
                    status = get();
                    if (status) {
                        model.addElement("Import terminated!");
                    }
                } catch (InterruptedException | ExecutionException ex) {
                    LoggerMgr.logInfo(ex.getLocalizedMessage());
                }
            }
        };

        // Call the SwingWorker from within the Swing thread
        worker.execute();
    }

    private void clearAction() {
        DefaultListModel<String> model = (DefaultListModel<String>) output.getModel();
        if (model != null) {
            cmbImportMgr.setSelectedIndex(-1);
            model.removeAllElements();
            model.addElement("Select Importer");
            progressBar.setValue(0);
        }

    }

    @Override
    public void setProgress(int progress) {
        progressBar.setValue(progress);
    }
}
